
function toPascalCase(value: string): string {
	const separated = value
		.replace(/([a-z0-9])([A-Z])/g, "$1 $2")
		.replace(/[^A-Za-z0-9]+/g, " ")
		.trim();

	if (!separated) {
		return "";
	}

	return separated
		.split(/\s+/g)
		.map((part) => part.charAt(0).toUpperCase() + part.slice(1))
		.join("");
}

export type InterfaceNameMap = Record<string, string>;

export const interfaceNameMap: InterfaceNameMap = {
	A1: "ArticleStats",
	A2: "ArticleListItem",
	A3: "BattleSideSummary",
	A4: "EquipmentSkillsDefensive",
	A5: "RoundEquipment",
	A6: "RoundLastHit",
	A7: "RoundSideCombatStats",
	A8: "RoundLiveState",
	A9: "BattleCurrentRound",
	A10: "BattleDefenderSummary",
	A11: "BattleStats",
	A12: "BattleListItem",
	A13: "BattleDetailedAttacker",
	A14: "BattleDetailedDefender",
	A15: "LiveBattleSummary",
	A16: "LiveRoundSummary",
	A17: "CompanyActiveUpgradeLevels",
	A18: "CompanyDates",
	A19: "RankingValueTier",
	A20: "CountryRankingsOptionalCitizenDamage",
	A21: "CountryResourceBonuses",
	A22: "CountryStrategicResources",
	A23: "CountryStrategicResourceConfig",
	A24: "CountryTaxes",
	A25: "CountryUnrestOptionalContributionDate",
	A26: "CountryListItem",
	A27: "CountryRankings",
	A28: "CountryUnrest",
	A29: "EventData",
	A30: "EventListItem",
	A31: "BadgeRewardWithPreserve",
	A32: "BadgeReward",
	A33: "BadgeRewardWithMetadata",
	A34: "GameConfigBadges",
	A35: "BattleTickPoints",
	A36: "GameConfigBattle",
	A37: "GameConfigCitizenshipApplication",
	A38: "GameConfigCompany",
	A39: "GameConfigCountry",
	A40: "GameConfigElection",
	A41: "GameConfigGovernment",
	A42: "ItemFlatStatsPercentAttack",
	A43: "ItemProductionNeedsLead",
	A44: "ItemAmmo",
	A45: "ItemDynamicStatsDodge",
	A46: "ItemBoots",
	A47: "ItemFlatStatsHealthRegen",
	A48: "ItemIconComponent",
	A49: "ItemProductionNeedsGrain",
	A50: "ItemBread",
	A51: "ItemCase",
	A52: "ItemDynamicStatsArmor",
	A53: "ItemChestOrPants",
	A54: "ItemDepositResource",
	A55: "ItemFlatStatsCocain",
	A56: "ItemProductionNeedsCoca",
	A57: "ItemCocain",
	A58: "ItemProductionNeedsLimestone",
	A59: "ItemConcrete",
	A60: "ItemProductionNeedsFish",
	A61: "ItemCookedFish",
	A62: "ItemDynamicStatsPrecision",
	A63: "ItemGloves",
	A64: "ItemDynamicStatsWeaponBase",
	A65: "ItemWeaponMeleeOrHeavy",
	A66: "ItemHeavyAmmo",
	A67: "ItemDynamicStatsCriticalDamages",
	A68: "ItemHelmet",
	A69: "ItemRawResource",
	A70: "ItemRifleLike",
	A71: "ItemProductionNeedsPetroleum",
	A72: "ItemOil",
	A73: "ItemScraps",
	A74: "ItemProductionNeedsLivestock",
	A75: "ItemSteak",
	A76: "ItemProductionNeedsIron",
	A77: "ItemSteel",
	A78: "GameConfigItems",
	A79: "LawActionCostAndMaintenance",
	A80: "LawActionCost",
	A81: "GameConfigLaw",
	A82: "MergingCostByRarity",
	A83: "MissionRerollCostByLevel",
	A84: "MissionRewardConfig",
	A85: "MissionRewardByPeriod",
	A86: "GameConfigMission",
	A87: "GameConfigMu",
	A88: "GameConfigNewspaper",
	A89: "GameConfigOrg",
	A90: "GameConfigParty",
	A91: "GameConfigReferral",
	A92: "RegionResourceBonusByTier",
	A93: "GameConfigRegion",
	A94: "SkillLevelZero",
	A95: "SkillLevel",
	A96: "SkillLevels",
	A97: "SkillTrack",
	A98: "BarSkillLevelZero",
	A99: "BarSkillLevels",
	A100: "BarSkillTrack",
	A101: "GameConfigSkills",
	A102: "GameConfigUnrest",
	A103: "GameConfigUpgrade",
	A104: "UpgradeConfigStorageStats",
	A105: "UpgradeConfigStorageLevel",
	A106: "UpgradeConfigStorageLevels",
	A107: "UpgradeConfigAutomatedEngine",
	A108: "UpgradeConfigAttackBonusStats",
	A109: "UpgradeConfigBaseLevel",
	A110: "UpgradeConfigBaseLevels",
	A111: "UpgradeConfigBase",
	A112: "UpgradeConfigBreakRoomStats",
	A113: "UpgradeConfigBreakRoomLevel",
	A114: "UpgradeConfigBreakRoomLevels",
	A115: "UpgradeConfigBreakRoom",
	A116: "UpgradeConfigDefenseBonusStats",
	A117: "UpgradeConfigBunkerLevel",
	A118: "UpgradeConfigBunkerLevels",
	A119: "UpgradeConfigBunker",
	A120: "UpgradeConfigDormitoriesStats",
	A121: "UpgradeConfigDormitoriesLevel",
	A122: "UpgradeConfigDormitoriesLevels",
	A123: "UpgradeConfigDormitories",
	A124: "UpgradeConfigHeadquartersLevel",
	A125: "UpgradeConfigHeadquartersLevels",
	A126: "UpgradeConfigHeadquarters",
	A127: "UpgradeConfigPacificationCenterStats",
	A128: "UpgradeConfigPacificationCenterLevel",
	A129: "UpgradeConfigPacificationCenterLevels",
	A130: "UpgradeConfigPacificationCenter",
	A131: "UpgradeConfigStorageCapacityStats",
	A132: "UpgradeConfigStorageCapacityLevel",
	A133: "UpgradeConfigStorageCapacityLevels",
	A134: "UpgradeConfigStorage",
	A135: "GameConfigUpgradesConfig",
	A136: "UserDailyReward",
	A137: "UserEquipmentSets",
	A138: "GameConfigUser",
	A139: "GameConfigWorker",
	A140: "MuActiveUpgradeLevels",
	A141: "MuRankings",
	A142: "MuRoles",
	A143: "MuActiveUpgradeLevelsOptional",
	A144: "MuRankingsOptional",
	A145: "MuListItem",
	A146: "RankingItem",
	A147: "RankingTierValues",
	A148: "RegionActiveUpgradeLevels",
	A149: "RegionDates",
	A150: "RegionDeposit",
	A151: "RegionStats",
	A152: "RegionUpgradeBase",
	A153: "RegionUpgradeConstructionHistory",
	A154: "RegionUpgradeBunker",
	A155: "RegionUpgrades",
	A156: "RegionUpgradesV2",
	A157: "RegionByIdItem",
	A158: "BattleSideSummaryRequiredRegion",
	A159: "RegionActiveBattle",
	A160: "RegionsObjectItem",
	A161: "WeaponSkills",
	A162: "RoundWeapon",
	A163: "RoundLastHitWithWeapon",
	A164: "RoundSideCombatStatsWithWeapon",
	A165: "TradingOrder",
	A166: "EquipmentSkillsMixed",
	A167: "TransactionItem",
	A168: "TransactionListItem",
	A169: "UserDates",
	A170: "UserInfos",
	A171: "UserLeveling",
	A172: "UserRankings",
	A173: "UserSkillComputedStandard",
	A174: "UserSkillComputedAttack",
	A175: "UserSkillComputedCompany",
	A176: "UserSkillComputedCriticalChance",
	A177: "UserSkillComputedBar",
	A178: "UserSkills",
	A179: "UserStats",
	A180: "UsersByCountryItem",
	A181: "WorkerCompany",
	A182: "WorkersPerCompanyItem",
	A183: "WorkOfferListItem",
};

function normalizeMappedName(value: string): string {
	return toPascalCase(value);
}

export function buildInterfaceName(interfaceId: string, nameMap?: InterfaceNameMap): string {
	if (!nameMap) {
		return interfaceId;
	}

	const mappedName = nameMap[interfaceId];
	if (!mappedName) {
		return interfaceId;
	}

	const normalized = normalizeMappedName(mappedName);
	return normalized || interfaceId;
}

export function buildTypeName(group: string, name: string): string {
	return `${toPascalCase(group)}${toPascalCase(name)}Response`;
}