
function toPascalCase(value: string): string {
	const separated = value
		.replace(/([a-z0-9])([A-Z])/g, "$1 $2")
		.replace(/[^A-Za-z0-9]+/g, " ")
		.trim();

	if (!separated) {
		return "";
	}

	return separated
		.split(/\s+/g)
		.map((part) => part.charAt(0).toUpperCase() + part.slice(1))
		.join("");
}

export type InterfaceNameMap = Record<string, string>;

export const interfaceNameMap: InterfaceNameMap = {
	A1: "ArticleStats",
	A2: "ArticleListItem",
	A3: "BattleSideSummary",
	A4: "EquipmentSkillsDefensive",
	A5: "RoundEquipment",
	A6: "WeaponSkills",
	A7: "RoundWeapon",
	A8: "RoundLastHit",
	A9: "RoundSideCombatStats",
	A10: "RoundSideCombatStatsOptionalHitCount",
	A11: "RoundLiveState",
	A12: "BattleCurrentRound",
	A13: "BattleDefenderSummary",
	A14: "BattleStats",
	A15: "BattleListItem",
	A16: "BattleDetailedSide",
	A17: "LiveBattleSummary",
	A18: "LiveRoundSummary",
	A19: "CompanyActiveUpgradeLevels",
	A20: "RankingValueTier",
	A21: "CountryRankingsOptionalCitizenDamage",
	A22: "CountryResourceBonuses",
	A23: "CountryStrategicResources",
	A24: "CountryStrategicResourceConfig",
	A25: "CountryTaxes",
	A26: "CountryUnrestOptionalContributionDate",
	A27: "CountryListItem",
	A28: "CountryRankings",
	A29: "CountryStrategicResourcesGoldOnly",
	A30: "CountryStrategicResourceConfigGoldOnly",
	A31: "CountryUnrest",
	A32: "EventData",
	A33: "EventListItem",
	A34: "BadgeRewardWithPreserve",
	A35: "BadgeReward",
	A36: "BadgeRewardWithMetadata",
	A37: "GameConfigBadges",
	A38: "BattleTickPoints",
	A39: "GameConfigBattle",
	A40: "GameConfigCitizenshipApplication",
	A41: "GameConfigCompany",
	A42: "GameConfigCountry",
	A43: "GameConfigElection",
	A44: "GameConfigGovernment",
	A45: "ItemFlatStatsPercentAttack",
	A46: "ItemProductionNeedsLead",
	A47: "ItemAmmo",
	A48: "ItemDynamicStatsDodge",
	A49: "ItemBoots",
	A50: "ItemFlatStatsHealthRegen",
	A51: "ItemIconComponent",
	A52: "ItemProductionNeedsGrain",
	A53: "ItemBread",
	A54: "ItemCase",
	A55: "ItemDynamicStatsArmor",
	A56: "ItemChestOrPants",
	A57: "ItemDepositResource",
	A58: "ItemFlatStatsCocain",
	A59: "ItemProductionNeedsCoca",
	A60: "ItemCocain",
	A61: "ItemProductionNeedsLimestone",
	A62: "ItemConcrete",
	A63: "ItemProductionNeedsFish",
	A64: "ItemCookedFish",
	A65: "ItemDynamicStatsPrecision",
	A66: "ItemGloves",
	A67: "ItemDynamicStatsWeaponBase",
	A68: "ItemWeaponMeleeOrHeavy",
	A69: "ItemHeavyAmmo",
	A70: "ItemDynamicStatsCriticalDamages",
	A71: "ItemHelmet",
	A72: "ItemRawResource",
	A73: "ItemRifleLike",
	A74: "ItemProductionNeedsPetroleum",
	A75: "ItemOil",
	A76: "ItemScraps",
	A77: "ItemProductionNeedsLivestock",
	A78: "ItemSteak",
	A79: "ItemProductionNeedsIron",
	A80: "ItemSteel",
	A81: "GameConfigItems",
	A82: "LawActionCostAndMaintenance",
	A83: "LawActionCost",
	A84: "GameConfigLaw",
	A85: "MergingCostByRarity",
	A86: "MissionRerollCostByLevel",
	A87: "MissionRewardConfig",
	A88: "MissionRewardByPeriod",
	A89: "GameConfigMission",
	A90: "GameConfigMu",
	A91: "GameConfigNewspaper",
	A92: "GameConfigOrg",
	A93: "GameConfigParty",
	A94: "GameConfigReferral",
	A95: "RegionResourceBonusByTier",
	A96: "GameConfigRegion",
	A97: "SkillLevelZero",
	A98: "SkillLevel",
	A99: "SkillLevels",
	A100: "SkillTrack",
	A101: "BarSkillLevelZero",
	A102: "BarSkillLevels",
	A103: "BarSkillTrack",
	A104: "GameConfigSkills",
	A105: "GameConfigUnrest",
	A106: "GameConfigUpgrade",
	A107: "UpgradeConfigStorageStats",
	A108: "UpgradeConfigStorageLevel",
	A109: "UpgradeConfigStorageLevels",
	A110: "UpgradeConfigAutomatedEngine",
	A111: "UpgradeConfigAttackBonusStats",
	A112: "UpgradeConfigBaseLevel",
	A113: "UpgradeConfigBaseLevels",
	A114: "UpgradeConfigBase",
	A115: "UpgradeConfigBreakRoomStats",
	A116: "UpgradeConfigBreakRoomLevel",
	A117: "UpgradeConfigBreakRoomLevels",
	A118: "UpgradeConfigBreakRoom",
	A119: "UpgradeConfigDefenseBonusStats",
	A120: "UpgradeConfigBunkerLevel",
	A121: "UpgradeConfigBunkerLevels",
	A122: "UpgradeConfigBunker",
	A123: "UpgradeConfigDormitoriesStats",
	A124: "UpgradeConfigDormitoriesLevel",
	A125: "UpgradeConfigDormitoriesLevels",
	A126: "UpgradeConfigDormitories",
	A127: "UpgradeConfigHeadquartersLevel",
	A128: "UpgradeConfigHeadquartersLevels",
	A129: "UpgradeConfigHeadquarters",
	A130: "UpgradeConfigPacificationCenterStats",
	A131: "UpgradeConfigPacificationCenterLevel",
	A132: "UpgradeConfigPacificationCenterLevels",
	A133: "UpgradeConfigPacificationCenter",
	A134: "UpgradeConfigStorageCapacityStats",
	A135: "UpgradeConfigStorageCapacityLevel",
	A136: "UpgradeConfigStorageCapacityLevels",
	A137: "UpgradeConfigStorage",
	A138: "GameConfigUpgradesConfig",
	A139: "UserDailyReward",
	A140: "UserEquipmentSets",
	A141: "GameConfigUser",
	A142: "GameConfigWorker",
	A143: "MuActiveUpgradeLevels",
	A144: "MuRankings",
	A145: "MuRoles",
	A146: "MuRankingsOptional",
	A147: "MuListItem",
	A148: "RankingItem",
	A149: "RankingTierValues",
	A150: "RegionActiveUpgradeLevels",
	A151: "RegionDates",
	A152: "RegionDeposit",
	A153: "RegionStats",
	A154: "RegionUpgradeConstructionHistory",
	A155: "RegionUpgradeBunker",
	A156: "RegionUpgrades",
	A157: "RegionUpgradesV2",
	A158: "RegionByIdItem",
	A159: "BattleSideSummaryRequiredRegion",
	A160: "RegionActiveBattle",
	A161: "RegionsObjectItem",
	A162: "RoundLastHitWithWeapon",
	A163: "RoundSideCombatStatsWithWeapon",
	A164: "TradingOrderWithMu",
	A165: "TradingOrder",
	A166: "EquipmentSkillsMixed",
	A167: "TransactionItem",
	A168: "TransactionListItem",
	A169: "UserDates",
	A170: "UserLeveling",
	A171: "UserRankings",
	A172: "UserSkillComputedStandard",
	A173: "UserSkillComputedAttack",
	A174: "UserSkillComputedCompany",
	A175: "UserSkillComputedCriticalChance",
	A176: "UserSkillComputedPrecision",
	A177: "UserSkillComputedBar",
	A178: "UserSkills",
	A179: "UserStats",
	A180: "UsersByCountryItem",
	A181: "WorkerCompany",
	A182: "WorkersPerCompanyItem",
	A183: "WorkOfferListItem",
};

function normalizeMappedName(value: string): string {
	return toPascalCase(value);
}

export function buildInterfaceName(interfaceId: string, nameMap?: InterfaceNameMap): string {
	if (!nameMap) {
		return interfaceId;
	}

	const mappedName = nameMap[interfaceId];
	if (!mappedName) {
		return interfaceId;
	}

	const normalized = normalizeMappedName(mappedName);
	return normalized || interfaceId;
}

export function buildTypeName(group: string, name: string): string {
	return `${toPascalCase(group)}${toPascalCase(name)}Response`;
}