
function toPascalCase(value: string): string {
	const separated = value
		.replace(/([a-z0-9])([A-Z])/g, "$1 $2")
		.replace(/[^A-Za-z0-9]+/g, " ")
		.trim();

	if (!separated) {
		return "";
	}

	return separated
		.split(/\s+/g)
		.map((part) => part.charAt(0).toUpperCase() + part.slice(1))
		.join("");
}

export type InterfaceNameMap = Record<string, string>;

export const interfaceNameMap: InterfaceNameMap = {
	A1: "ArticleStats",
	A2: "ArticleListItem",
	A3: "BattleSideSummary",
	A4: "EquipmentSkillsDefensive",
	A5: "RoundEquipment",
	A6: "WeaponSkills",
	A7: "RoundWeapon",
	A8: "RoundLastHit",
	A9: "RoundSideCombatStats",
	A10: "RoundLiveState",
	A11: "BattleCurrentRound",
	A12: "BattleDefenderSummary",
	A13: "BattleStats",
	A14: "BattleListItem",
	A15: "BattleDetailedSide",
	A16: "LiveBattleSummary",
	A17: "LiveRoundSummary",
	A18: "CompanyActiveUpgradeLevels",
	A19: "CompanyDates",
	A20: "RankingValueTier",
	A21: "CountryRankingsOptionalCitizenDamage",
	A22: "CountryResourceBonuses",
	A23: "CountryStrategicResources",
	A24: "CountryStrategicResourceConfig",
	A25: "CountryTaxes",
	A26: "CountryUnrestOptionalContributionDate",
	A27: "CountryListItem",
	A28: "CountryRankings",
	A29: "CountryUnrest",
	A30: "EventData",
	A31: "EventListItem",
	A32: "BadgeRewardWithPreserve",
	A33: "BadgeReward",
	A34: "BadgeRewardWithMetadata",
	A35: "GameConfigBadges",
	A36: "BattleTickPoints",
	A37: "GameConfigBattle",
	A38: "GameConfigCitizenshipApplication",
	A39: "GameConfigCompany",
	A40: "GameConfigCountry",
	A41: "GameConfigElection",
	A42: "GameConfigGovernment",
	A43: "ItemFlatStatsPercentAttack",
	A44: "ItemProductionNeedsLead",
	A45: "ItemAmmo",
	A46: "ItemDynamicStatsDodge",
	A47: "ItemBoots",
	A48: "ItemFlatStatsHealthRegen",
	A49: "ItemIconComponent",
	A50: "ItemProductionNeedsGrain",
	A51: "ItemBread",
	A52: "ItemCase",
	A53: "ItemDynamicStatsArmor",
	A54: "ItemChestOrPants",
	A55: "ItemDepositResource",
	A56: "ItemFlatStatsCocain",
	A57: "ItemProductionNeedsCoca",
	A58: "ItemCocain",
	A59: "ItemProductionNeedsLimestone",
	A60: "ItemConcrete",
	A61: "ItemProductionNeedsFish",
	A62: "ItemCookedFish",
	A63: "ItemDynamicStatsPrecision",
	A64: "ItemGloves",
	A65: "ItemDynamicStatsWeaponBase",
	A66: "ItemWeaponMeleeOrHeavy",
	A67: "ItemHeavyAmmo",
	A68: "ItemDynamicStatsCriticalDamages",
	A69: "ItemHelmet",
	A70: "ItemRawResource",
	A71: "ItemRifleLike",
	A72: "ItemProductionNeedsPetroleum",
	A73: "ItemOil",
	A74: "ItemScraps",
	A75: "ItemProductionNeedsLivestock",
	A76: "ItemSteak",
	A77: "ItemProductionNeedsIron",
	A78: "ItemSteel",
	A79: "GameConfigItems",
	A80: "LawActionCostAndMaintenance",
	A81: "LawActionCost",
	A82: "GameConfigLaw",
	A83: "MergingCostByRarity",
	A84: "MissionRerollCostByLevel",
	A85: "MissionRewardConfig",
	A86: "MissionRewardByPeriod",
	A87: "GameConfigMission",
	A88: "GameConfigMu",
	A89: "GameConfigNewspaper",
	A90: "GameConfigOrg",
	A91: "GameConfigParty",
	A92: "GameConfigReferral",
	A93: "RegionResourceBonusByTier",
	A94: "GameConfigRegion",
	A95: "SkillLevelZero",
	A96: "SkillLevel",
	A97: "SkillLevels",
	A98: "SkillTrack",
	A99: "BarSkillLevelZero",
	A100: "BarSkillLevels",
	A101: "BarSkillTrack",
	A102: "GameConfigSkills",
	A103: "GameConfigUnrest",
	A104: "GameConfigUpgrade",
	A105: "UpgradeConfigStorageStats",
	A106: "UpgradeConfigStorageLevel",
	A107: "UpgradeConfigStorageLevels",
	A108: "UpgradeConfigAutomatedEngine",
	A109: "UpgradeConfigAttackBonusStats",
	A110: "UpgradeConfigBaseLevel",
	A111: "UpgradeConfigBaseLevels",
	A112: "UpgradeConfigBase",
	A113: "UpgradeConfigBreakRoomStats",
	A114: "UpgradeConfigBreakRoomLevel",
	A115: "UpgradeConfigBreakRoomLevels",
	A116: "UpgradeConfigBreakRoom",
	A117: "UpgradeConfigDefenseBonusStats",
	A118: "UpgradeConfigBunkerLevel",
	A119: "UpgradeConfigBunkerLevels",
	A120: "UpgradeConfigBunker",
	A121: "UpgradeConfigDormitoriesStats",
	A122: "UpgradeConfigDormitoriesLevel",
	A123: "UpgradeConfigDormitoriesLevels",
	A124: "UpgradeConfigDormitories",
	A125: "UpgradeConfigHeadquartersLevel",
	A126: "UpgradeConfigHeadquartersLevels",
	A127: "UpgradeConfigHeadquarters",
	A128: "UpgradeConfigPacificationCenterStats",
	A129: "UpgradeConfigPacificationCenterLevel",
	A130: "UpgradeConfigPacificationCenterLevels",
	A131: "UpgradeConfigPacificationCenter",
	A132: "UpgradeConfigStorageCapacityStats",
	A133: "UpgradeConfigStorageCapacityLevel",
	A134: "UpgradeConfigStorageCapacityLevels",
	A135: "UpgradeConfigStorage",
	A136: "GameConfigUpgradesConfig",
	A137: "UserDailyReward",
	A138: "UserEquipmentSets",
	A139: "GameConfigUser",
	A140: "GameConfigWorker",
	A141: "MuActiveUpgradeLevels",
	A142: "MuRankings",
	A143: "MuRoles",
	A144: "MuActiveUpgradeLevelsOptional",
	A145: "MuRankingsOptional",
	A146: "MuListItem",
	A147: "RankingItem",
	A148: "RankingTierValues",
	A149: "RegionActiveUpgradeLevels",
	A150: "RegionDates",
	A151: "RegionDeposit",
	A152: "RegionStats",
	A153: "RegionUpgradeBase",
	A154: "RegionUpgradeConstructionHistory",
	A155: "RegionUpgradeBunker",
	A156: "RegionUpgrades",
	A157: "RegionUpgradesV2",
	A158: "RegionByIdItem",
	A159: "BattleSideSummaryRequiredRegion",
	A160: "RegionActiveBattle",
	A161: "RegionsObjectItem",
	A162: "RoundLastHitWithWeapon",
	A163: "RoundSideCombatStatsWithWeapon",
	A164: "TradingOrder",
	A165: "EquipmentSkillsMixed",
	A166: "TransactionItem",
	A167: "TransactionListItem",
	A168: "UserDates",
	A169: "UserInfos",
	A170: "UserLeveling",
	A171: "UserRankings",
	A172: "UserSkillComputedStandard",
	A173: "UserSkillComputedAttack",
	A174: "UserSkillComputedCompany",
	A175: "UserSkillComputedCriticalChance",
	A176: "UserSkillComputedBar",
	A177: "UserSkills",
	A178: "UserStats",
	A179: "UsersByCountryItem",
	A180: "WorkerCompany",
	A181: "WorkersPerCompanyItem",
	A182: "WorkOfferListItem",
};

function normalizeMappedName(value: string): string {
	return toPascalCase(value);
}

export function buildInterfaceName(interfaceId: string, nameMap?: InterfaceNameMap): string {
	if (!nameMap) {
		return interfaceId;
	}

	const mappedName = nameMap[interfaceId];
	if (!mappedName) {
		return interfaceId;
	}

	const normalized = normalizeMappedName(mappedName);
	return normalized || interfaceId;
}

export function buildTypeName(group: string, name: string): string {
	return `${toPascalCase(group)}${toPascalCase(name)}Response`;
}