// Generated by tests/convert_to_types.ts

export type ArticleGetArticleByIdResponse = {
  __v: number;
  _id: string;
  author: string;
  category: string;
  content: string;
  createdAt: string;
  isDeleted: boolean;
  isPublished: boolean;
  language: string;
  publishedAt: string;
  stats: {
    comments: number;
    dislikes: number;
    gemTips: number;
    likes: number;
    score: number;
    subs: number;
    tips: number;
    views: number;
  };
  title: string;
  updatedAt: string;
};

export type ArticleGetArticleLiteByIdResponse = {
  _id: string;
  stats: {
    comments: number;
    dislikes: number;
    gemTips: number;
    likes: number;
    score: number;
    subs: number;
    tips: number;
    views: number;
  };
  title: string;
};

export type ArticleGetArticlesPaginatedResponse = {
  items: Array<{
    __v: number;
    _id: string;
    author: string;
    category: string;
    content: string;
    createdAt: string;
    isDeleted: boolean;
    isPublished: boolean;
    language: string;
    publishedAt: string;
    stats: {
      comments: number;
      dislikes: number;
      gemTips: number;
      likes: number;
      score: number;
      subs: number;
      tips: number;
      views: number;
    };
    title: string;
    updatedAt: string;
  }>;
  nextCursor: string;
};

export type BattleGetBattlesResponse = {
  items: Array<{
    __v: number;
    _id: string;
    attacker: {
      country: string;
      countryOrders: Array<string>;
      damages: number;
      hitCount: number;
      moneyPer1kDamages?: number;
      moneyPool?: number;
      muOrders: Array<string>;
      region?: string;
      wonRoundsCount: number;
    };
    createdAt: string;
    currentRound: {
      __v: number;
      _id: string;
      attacker: {
        country: string;
        damages: number;
        hitCount: number;
        lastHits: Array<{
          _id: string;
          ammo: unknown;
          damages: number;
          equipments: Array<{
            _id: string;
            code: string;
            lastAcquisitionAt: string;
            maxState: number;
            quantity: number;
            skills: {
              armor?: number;
              criticalDamages?: number;
              dodge?: number;
              precision?: number;
            };
            state: number;
            type: string;
          }>;
          hitAt: string;
          isCriticalHit: boolean;
          isMissed: boolean;
          mu: unknown;
          user: string;
          weapon: unknown;
        }>;
        points: number;
      };
      battle: string;
      createdAt: string;
      defender: {
        country: string;
        damages: number;
        hitCount?: number;
        lastHits: Array<{
          _id: string;
          ammo: unknown;
          damages: number;
          equipments: Array<{
            _id: string;
            code: string;
            lastAcquisitionAt: string;
            maxState: number;
            quantity: number;
            skills: {
              armor?: number;
              criticalDamages?: number;
              dodge?: number;
              precision?: number;
            };
            state: number;
            type: string;
          }>;
          hitAt: string;
          isCriticalHit: boolean;
          isMissed: boolean;
          mu: unknown;
          user: string;
          weapon: unknown;
        }>;
        points: number;
      };
      isActive: boolean;
      live: {
        actualTickPoints: number;
        nextTickAt: string;
        ticksCount: number;
      };
      number: number;
      updatedAt: string;
    };
    defender: {
      country: string;
      countryOrders: Array<string>;
      damages: number;
      hitCount: number;
      moneyPer1kDamages?: number;
      moneyPool?: number;
      muOrders: Array<string>;
      region: string;
      wonRoundsCount: number;
    };
    isActive: boolean;
    rounds: Array<string>;
    roundsHistory: Array<string>;
    roundsToWin: number;
    stats: {
      hitCount: number;
    };
    type: string;
    updatedAt: string;
    war: string;
  }>;
  nextCursor: string;
};

export type BattleGetByIdResponse = {
  __v: number;
  _id: string;
  attacker: {
    country: string;
    countryOrders: Array<string>;
    damages: number;
    hitCount: number;
    moneyPer1kDamages: number;
    moneyPool: number;
    muOrders: Array<string>;
    region: string;
    wonRoundsCount: number;
  };
  createdAt: string;
  currentRound: string;
  defender: {
    country: string;
    countryOrders: Array<string>;
    damages: number;
    hitCount: number;
    moneyPer1kDamages: number;
    muOrders: Array<string>;
    region: string;
    wonRoundsCount: number;
  };
  isActive: boolean;
  rounds: Array<string>;
  roundsHistory: Array<string>;
  roundsToWin: number;
  stats: {
    hitCount: number;
  };
  type: string;
  updatedAt: string;
  war: string;
};

export type BattleGetLiveBattleDataResponse = {
  battle: {
    attackerCountryOrders: Array<string>;
    attackerMoneyPer1kDamages: number;
    attackerMoneyPool: number;
    defenderCountryOrders: Array<string>;
    defenderMoneyPer1kDamages: number;
    isActive: boolean;
    roundHistory: Array<string>;
    roundIds: Array<string>;
  };
  round: {
    actualTickPoints: number;
    attackerDamages: number;
    attackerPoints: number;
    defenderDamages: number;
    defenderPoints: number;
    isActive: boolean;
    nextTickAt: string;
    roundId: string;
  };
};

export type BattleRankingGetRankingResponse = {
  rankings: Array<{
    country: string;
    value: number;
    rank: number;
    _id: string;
  }>;
};

export type CompanyGetByIdResponse = {
  __v: number;
  _id: string;
  activeUpgradeLevels: {
    automatedEngine: number;
    breakRoom: number;
    storage: number;
  };
  concreteInvested: number;
  createdAt: string;
  estimatedValue: number;
  isFull: boolean;
  itemCode: string;
  movedUpAt: string;
  name: string;
  production: number;
  region: string;
  updatedAt: string;
  user: string;
  workerCount: number;
};

export type CompanyGetCompaniesResponse = {
  items: Array<string>;
  nextCursor: string;
};

export type CountryGetAllCountriesResponse = Array<{
  __v: number;
  _id: string;
  allies: Array<string>;
  code: string;
  createdAt?: string;
  currentBattleOrder?: string;
  development: number;
  discordUrl?: string;
  enemy?: unknown;
  mapAccent: string;
  money: number;
  name: string;
  orgs: Array<string>;
  pinnedArticle?: string;
  rankings: {
    countryActivePopulation: {
      rank: number;
      tier: string;
      value: number;
    };
    countryBounty: {
      rank: number;
      tier: string;
      value: number;
    };
    countryDamages: {
      rank: number;
      tier: string;
      value: number;
    };
    countryDevelopment: {
      rank: number;
      tier: string;
      value: number;
    };
    countryProductionBonus: {
      rank: number;
      tier: string;
      value: number;
    };
    countryRegionDiff: {
      rank: number;
      tier: string;
      value: number;
    };
    countryWealth: {
      rank: number;
      tier: string;
      value: number;
    };
    weeklyCountryDamages: {
      rank: number;
      tier: string;
      value: number;
    };
    weeklyCountryDamagesPerCitizen?: {
      rank: number;
      tier: string;
      value: number;
    };
  };
  rulingParty?: unknown;
  scheme: string;
  specializedItem?: string;
  strategicResources?: {
    bonuses: {
      developmentPercent: number;
      productionPercent: number;
    };
    resources: {
      coal?: Array<string>;
      diamonds?: Array<string>;
      gold?: Array<string>;
      lithium?: Array<string>;
      rareEarths?: Array<string>;
      uranium?: Array<string>;
    };
  };
  taxes: {
    income: number;
    market: number;
    selfWork: number;
  };
  unrest: {
    bar: number;
    barMax: number;
    lastContributionAt?: string;
  };
  updatedAt: string;
  warsWith: Array<string>;
}>;

export type CountryGetCountryByIdResponse = {
  __v: number;
  _id: string;
  allies: Array<string>;
  code: string;
  createdAt: string;
  development: number;
  discordUrl: string;
  mapAccent: string;
  money: number;
  name: string;
  orgs: unknown[];
  rankings: {
    countryActivePopulation: {
      rank: number;
      tier: string;
      value: number;
    };
    countryBounty: {
      rank: number;
      tier: string;
      value: number;
    };
    countryDamages: {
      rank: number;
      tier: string;
      value: number;
    };
    countryDevelopment: {
      rank: number;
      tier: string;
      value: number;
    };
    countryProductionBonus: {
      rank: number;
      tier: string;
      value: number;
    };
    countryRegionDiff: {
      rank: number;
      tier: string;
      value: number;
    };
    countryWealth: {
      rank: number;
      tier: string;
      value: number;
    };
    weeklyCountryDamages: {
      rank: number;
      tier: string;
      value: number;
    };
    weeklyCountryDamagesPerCitizen: {
      rank: number;
      tier: string;
      value: number;
    };
  };
  rulingParty: string;
  scheme: string;
  specializedItem: string;
  taxes: {
    income: number;
    market: number;
    selfWork: number;
  };
  unrest: {
    bar: number;
    barMax: number;
    lastContributionAt: string;
  };
  updatedAt: string;
  warsWith: Array<string>;
};

export type EventGetEventsPaginatedResponse = {
  items: Array<{
    __v: number;
    _id: string;
    countries: Array<string>;
    createdAt: string;
    data: {
      amount?: number;
      attackerCountry?: string;
      battle?: string;
      bonusPercent?: number;
      countries?: Array<string>;
      defenderCountry?: string;
      defenderRegion?: string;
      durationDays?: number;
      itemCode?: string;
      money?: number;
      region?: string;
      regions?: Array<string>;
      type: string;
    };
    priority: string;
    updatedAt: string;
  }>;
  nextCursor: string;
};

export type GameConfigGetDatesResponse = {
  dailyMissionRegenAt: string;
  nextCongressElectionsAt: string;
  nextDayAt: string;
  nextMonthAt: string;
  nextPresidentialElectionsAt: string;
  nextRegenAt: string;
  previousDayAt: string;
  weeklyMissionRegenAt: string;
};

export type GameConfigGetGameConfigResponse = {
  badge: {
    alphaTester: {
      preserveBetweenReset: boolean;
      reward: number;
    };
    babyBoomer: {
      preserveBetweenReset: boolean;
      reward: number;
    };
    battleTerrainTop1: {
      reward: number;
    };
    battleTop1: {
      reward: number;
    };
    bugFinder: {
      preserveBetweenReset: boolean;
      reward: number;
    };
    coffee: {
      preserveBetweenReset: boolean;
      reward: number;
    };
    congressMember: {
      reward: number;
    };
    countryPresident: {
      reward: number;
    };
    countryTournamentWinner: {
      preserveBetweenReset: boolean;
      reward: number;
    };
    foundingFather: {
      preserveBetweenReset: boolean;
      reward: number;
    };
    giftPremium: {
      preserveBetweenReset: boolean;
      reward: number;
    };
    giveawayWinner: {
      reward: number;
    };
    hardWorker: {
      reward: number;
    };
    muTournamentWinner: {
      preserveBetweenReset: boolean;
      reward: number;
    };
    popularArticle: {
      preserveBetweenReset: boolean;
      reward: number;
      uniqueMetadataKey: string;
    };
    premium: {
      preserveBetweenReset: boolean;
      reward: number;
    };
    referral: {
      reward: number;
    };
    resetSurvivor: {
      preserveBetweenReset: boolean;
      reward: number;
    };
    roundTerrainTop1: {
      reward: number;
    };
    roundTop1: {
      reward: number;
    };
    staff: {
      preserveBetweenReset: boolean;
      reward: number;
    };
    sugarDaddy: {
      preserveBetweenReset: boolean;
      reward: number;
    };
    translator: {
      preserveBetweenReset: boolean;
      reward: number;
    };
    vicePresident: {
      reward: number;
    };
    voted: {
      reward: number;
    };
  };
  battle: {
    allianceDamagesBonusPercent: number;
    casesPer1kDamagesInPool: number;
    countryOrderBonusPercent: number;
    enemyDamagesBonusPercent: number;
    healthCost: number;
    hitFor1CaseInPool: number;
    lostAttackingRegionMalusPercent: number;
    maxRounds: number;
    muOrderBonusPercent: number;
    occupyingYourRegionsMalusPercent: number;
    patrioticBonusPercent: number;
    pointsToWinRound: number;
    regionNotLinkedToCapitalMalusPercent: number;
    roundsToWin: number;
    setCountryOrderMoneyCost: number;
    setMuOrderMoneyCost: number;
    setOrderMoneyCost: number;
    tickPoints: {
      "1": number;
      "100": number;
      "200": number;
      "300": number;
      "400": number;
      "500": number;
    };
  };
  citizenshipApplication: {
    autoApprovalEnabled: boolean;
    autoApprovalMaxPopulation: number;
  };
  company: {
    changeItemCost: number;
    constructionCostIncreasePerCompany: number;
    depositResourceBonus: number;
    destructionValuePercent: number;
    moveCost: number;
  };
  country: {
    hijackedTaxPercentPerResistance: number;
    maxTaxAmount: number;
  };
  election: {
    candidateDurationHours: number;
    candidateMinLevel: number;
    electionVoteDurationHours: number;
    voteMinLevel: number;
  };
  government: {
    resistanceDecreasedCooldownInHours: number;
    resistanceIncreasedCooldownInHours: number;
  };
  items: {
    ammo: {
      code: string;
      flatStats: {
        percentAttack: number;
      };
      isTradable: boolean;
      productionNeeds: {
        lead: number;
      };
      productionPoints: number;
      rarity: string;
      skinSlot: string;
      type: string;
      usage: string;
    };
    boots1: {
      code: string;
      dynamicStats: {
        dodge: Array<number>;
      };
      iconImg: string;
      rarity: string;
      skinSlot: string;
      type: string;
      usage: string;
    };
    boots2: {
      code: string;
      dynamicStats: {
        dodge: Array<number>;
      };
      iconImg: string;
      rarity: string;
      skinSlot: string;
      type: string;
      usage: string;
    };
    boots3: {
      code: string;
      dynamicStats: {
        dodge: Array<number>;
      };
      iconImg: string;
      rarity: string;
      skinSlot: string;
      type: string;
      usage: string;
    };
    boots4: {
      code: string;
      dynamicStats: {
        dodge: Array<number>;
      };
      iconImg: string;
      rarity: string;
      skinSlot: string;
      type: string;
      usage: string;
    };
    boots5: {
      code: string;
      dynamicStats: {
        dodge: Array<number>;
      };
      iconImg: string;
      rarity: string;
      skinSlot: string;
      type: string;
      usage: string;
    };
    boots6: {
      code: string;
      dynamicStats: {
        dodge: Array<number>;
      };
      iconImg: string;
      rarity: string;
      skinSlot: string;
      type: string;
      usage: string;
    };
    bread: {
      code: string;
      flatStats: {
        healthRegen: number;
      };
      IconComponent: {
        compare: unknown;
      };
      isConsumable: boolean;
      isTradable: boolean;
      productionNeeds: {
        grain: number;
      };
      productionPoints: number;
      rarity: string;
      type: string;
    };
    case1: {
      code: string;
      isTradable: boolean;
      rarity: string;
      type: string;
      usage: string;
    };
    case2: {
      code: string;
      isTradable: boolean;
      rarity: string;
      type: string;
      usage: string;
    };
    chest1: {
      code: string;
      dynamicStats: {
        armor: Array<number>;
      };
      iconImg: string;
      rarity: string;
      skinSlot: string;
      type: string;
      usage: string;
    };
    chest2: {
      code: string;
      dynamicStats: {
        armor: Array<number>;
      };
      iconImg: string;
      rarity: string;
      skinSlot: string;
      type: string;
      usage: string;
    };
    chest3: {
      code: string;
      dynamicStats: {
        armor: Array<number>;
      };
      iconImg: string;
      rarity: string;
      skinSlot: string;
      type: string;
      usage: string;
    };
    chest4: {
      code: string;
      dynamicStats: {
        armor: Array<number>;
      };
      iconImg: string;
      rarity: string;
      skinSlot: string;
      type: string;
      usage: string;
    };
    chest5: {
      code: string;
      dynamicStats: {
        armor: Array<number>;
      };
      iconImg: string;
      rarity: string;
      skinSlot: string;
      type: string;
      usage: string;
    };
    chest6: {
      code: string;
      dynamicStats: {
        armor: Array<number>;
      };
      iconImg: string;
      rarity: string;
      skinSlot: string;
      type: string;
      usage: string;
    };
    coca: {
      climates: Array<string>;
      code: string;
      IconComponent: {
        compare: unknown;
      };
      isDeposit: boolean;
      isTradable: boolean;
      productionPoints: number;
      rarity: string;
      type: string;
    };
    cocain: {
      code: string;
      flatStats: {
        buffDurationHours: number;
        debuffDurationHours: number;
        percentAttack: number;
      };
      IconComponent: {
        compare: unknown;
      };
      isTradable: boolean;
      productionNeeds: {
        coca: number;
      };
      productionPoints: number;
      rarity: string;
      type: string;
    };
    concrete: {
      code: string;
      isTradable: boolean;
      productionNeeds: {
        limestone: number;
      };
      productionPoints: number;
      rarity: string;
      type: string;
    };
    cookedFish: {
      code: string;
      flatStats: {
        healthRegen: number;
      };
      isConsumable: boolean;
      isTradable: boolean;
      productionNeeds: {
        fish: number;
      };
      productionPoints: number;
      rarity: string;
      type: string;
    };
    fish: {
      climates: Array<string>;
      code: string;
      IconComponent: {
        compare: unknown;
      };
      isDeposit: boolean;
      isTradable: boolean;
      productionPoints: number;
      rarity: string;
      type: string;
    };
    gloves1: {
      code: string;
      dynamicStats: {
        precision: Array<number>;
      };
      iconImg: string;
      rarity: string;
      skinSlot: string;
      type: string;
      usage: string;
    };
    gloves2: {
      code: string;
      dynamicStats: {
        precision: Array<number>;
      };
      iconImg: string;
      rarity: string;
      skinSlot: string;
      type: string;
      usage: string;
    };
    gloves3: {
      code: string;
      dynamicStats: {
        precision: Array<number>;
      };
      iconImg: string;
      rarity: string;
      skinSlot: string;
      type: string;
      usage: string;
    };
    gloves4: {
      code: string;
      dynamicStats: {
        precision: Array<number>;
      };
      iconImg: string;
      rarity: string;
      skinSlot: string;
      type: string;
      usage: string;
    };
    gloves5: {
      code: string;
      dynamicStats: {
        precision: Array<number>;
      };
      iconImg: string;
      rarity: string;
      skinSlot: string;
      type: string;
      usage: string;
    };
    gloves6: {
      code: string;
      dynamicStats: {
        precision: Array<number>;
      };
      iconImg: string;
      rarity: string;
      skinSlot: string;
      type: string;
      usage: string;
    };
    grain: {
      climates: Array<string>;
      code: string;
      IconComponent: {
        compare: unknown;
      };
      isDeposit: boolean;
      isTradable: boolean;
      productionPoints: number;
      rarity: string;
      type: string;
    };
    gun: {
      code: string;
      dynamicStats: {
        attack: Array<number>;
        criticalChance: Array<number>;
      };
      IconComponent: {
        compare: unknown;
      };
      rarity: string;
      skinSlot: string;
      type: string;
      usage: string;
    };
    heavyAmmo: {
      code: string;
      flatStats: {
        percentAttack: number;
      };
      IconComponent: {
        compare: unknown;
      };
      isTradable: boolean;
      productionNeeds: {
        lead: number;
      };
      productionPoints: number;
      rarity: string;
      skinSlot: string;
      type: string;
      usage: string;
    };
    helmet1: {
      code: string;
      dynamicStats: {
        criticalDamages: Array<number>;
      };
      iconImg: string;
      rarity: string;
      skinSlot: string;
      type: string;
      usage: string;
    };
    helmet2: {
      code: string;
      dynamicStats: {
        criticalDamages: Array<number>;
      };
      iconImg: string;
      rarity: string;
      skinSlot: string;
      type: string;
      usage: string;
    };
    helmet3: {
      code: string;
      dynamicStats: {
        criticalDamages: Array<number>;
      };
      iconImg: string;
      rarity: string;
      skinSlot: string;
      type: string;
      usage: string;
    };
    helmet4: {
      code: string;
      dynamicStats: {
        criticalDamages: Array<number>;
      };
      iconImg: string;
      rarity: string;
      skinSlot: string;
      type: string;
      usage: string;
    };
    helmet5: {
      code: string;
      dynamicStats: {
        criticalDamages: Array<number>;
      };
      iconImg: string;
      rarity: string;
      skinSlot: string;
      type: string;
      usage: string;
    };
    helmet6: {
      code: string;
      dynamicStats: {
        criticalDamages: Array<number>;
      };
      iconImg: string;
      rarity: string;
      skinSlot: string;
      type: string;
      usage: string;
    };
    iron: {
      climates: Array<string>;
      code: string;
      isDeposit: boolean;
      isTradable: boolean;
      productionPoints: number;
      rarity: string;
      type: string;
    };
    jet: {
      code: string;
      dynamicStats: {
        attack: Array<number>;
        criticalChance: Array<number>;
      };
      rarity: string;
      skinSlot: string;
      type: string;
      usage: string;
    };
    knife: {
      code: string;
      dynamicStats: {
        attack: Array<number>;
        criticalChance: Array<number>;
      };
      IconComponent: {
        compare: unknown;
      };
      rarity: string;
      skinSlot: string;
      type: string;
      usage: string;
    };
    lead: {
      climates: Array<string>;
      code: string;
      isDeposit: boolean;
      isTradable: boolean;
      productionPoints: number;
      rarity: string;
      type: string;
    };
    lightAmmo: {
      code: string;
      flatStats: {
        percentAttack: number;
      };
      isTradable: boolean;
      productionNeeds: {
        lead: number;
      };
      productionPoints: number;
      rarity: string;
      skinSlot: string;
      type: string;
      usage: string;
    };
    limestone: {
      climates: Array<string>;
      code: string;
      isDeposit: boolean;
      isTradable: boolean;
      productionPoints: number;
      rarity: string;
      type: string;
    };
    livestock: {
      climates: Array<string>;
      code: string;
      IconComponent: {
        compare: unknown;
      };
      isDeposit: boolean;
      isTradable: boolean;
      productionPoints: number;
      rarity: string;
      type: string;
    };
    oil: {
      code: string;
      IconComponent: {
        compare: unknown;
      };
      isTradable: boolean;
      productionNeeds: {
        petroleum: number;
      };
      productionPoints: number;
      rarity: string;
      type: string;
    };
    pants1: {
      code: string;
      dynamicStats: {
        armor: Array<number>;
      };
      iconImg: string;
      rarity: string;
      skinSlot: string;
      type: string;
      usage: string;
    };
    pants2: {
      code: string;
      dynamicStats: {
        armor: Array<number>;
      };
      iconImg: string;
      rarity: string;
      skinSlot: string;
      type: string;
      usage: string;
    };
    pants3: {
      code: string;
      dynamicStats: {
        armor: Array<number>;
      };
      iconImg: string;
      rarity: string;
      skinSlot: string;
      type: string;
      usage: string;
    };
    pants4: {
      code: string;
      dynamicStats: {
        armor: Array<number>;
      };
      iconImg: string;
      rarity: string;
      skinSlot: string;
      type: string;
      usage: string;
    };
    pants5: {
      code: string;
      dynamicStats: {
        armor: Array<number>;
      };
      iconImg: string;
      rarity: string;
      skinSlot: string;
      type: string;
      usage: string;
    };
    pants6: {
      code: string;
      dynamicStats: {
        armor: Array<number>;
      };
      iconImg: string;
      rarity: string;
      skinSlot: string;
      type: string;
      usage: string;
    };
    petroleum: {
      climates: Array<string>;
      code: string;
      IconComponent: {
        compare: unknown;
      };
      isDeposit: boolean;
      isTradable: boolean;
      productionPoints: number;
      rarity: string;
      type: string;
    };
    rifle: {
      code: string;
      dynamicStats: {
        attack: Array<number>;
        criticalChance: Array<number>;
      };
      rarity: string;
      skinSlot: string;
      type: string;
      usage: string;
    };
    scraps: {
      code: string;
      isTradable: boolean;
      rarity: string;
      type: string;
    };
    sniper: {
      code: string;
      dynamicStats: {
        attack: Array<number>;
        criticalChance: Array<number>;
      };
      rarity: string;
      skinSlot: string;
      type: string;
      usage: string;
    };
    steak: {
      code: string;
      flatStats: {
        healthRegen: number;
      };
      IconComponent: {
        compare: unknown;
      };
      isConsumable: boolean;
      isTradable: boolean;
      productionNeeds: {
        livestock: number;
      };
      productionPoints: number;
      rarity: string;
      type: string;
    };
    steel: {
      code: string;
      isTradable: boolean;
      productionNeeds: {
        iron: number;
      };
      productionPoints: number;
      rarity: string;
      type: string;
    };
    tank: {
      code: string;
      dynamicStats: {
        attack: Array<number>;
        criticalChance: Array<number>;
      };
      IconComponent: {
        compare: unknown;
      };
      rarity: string;
      skinSlot: string;
      type: string;
      usage: string;
    };
  };
  law: {
    abusiveLawPossibleVotersNeeded: number;
    abusiveLawsCooldownInDays: number;
    accept_alliance: {
      cost: number;
      maintenanceCost: number;
    };
    define_enemy_country: {
      cost: number;
      maintenanceCost: number;
    };
    lawVotesDurationHours: number;
    propose_alliance: {
      cost: number;
      maintenanceCost: number;
    };
    set_color_scheme: {
      cost: number;
    };
    votersRatioNeeded: number;
  };
  mergingCost: {
    common: number;
    epic: number;
    legendary: number;
    mythic: number;
    rare: number;
    uncommon: number;
  };
  mission: {
    rerollMissionCost: {
      "0": number;
      "1": number;
      "10": number;
      "11": number;
      "12": number;
      "13": number;
      "14": number;
      "15": number;
      "16": number;
      "17": number;
      "18": number;
      "19": number;
      "2": number;
      "20": number;
      "3": number;
      "4": number;
      "5": number;
      "6": number;
      "7": number;
      "8": number;
      "9": number;
    };
    reward: {
      daily: {
        cases: number;
        money: number;
        xp: number;
        xpWhenFinished: number;
      };
      monthly: {
        cases: number;
        money: number;
        xp: number;
        xpWhenFinished: number;
      };
      starting: {
        cases: number;
        money: number;
        xp: number;
        xpWhenFinished: number;
      };
      weekly: {
        cases: number;
        money: number;
        xp: number;
        xpWhenFinished: number;
      };
    };
  };
  mu: {
    constructionCost: number;
    destructionValuePercent: number;
    healthPerHelp: number;
    helpCooldownHours: number;
    helpValue: number;
    maxOwnedMus: number;
    moveCost: number;
  };
  newspaper: {
    createArticleMinLevel: number;
    gemTipValue: number;
    publishCost: number;
    tipMinLevel: number;
    tipValue: number;
  };
  org: {
    constructionCost: number;
    moveCost: number;
  };
  party: {
    createCost: number;
  };
  referral: {
    canSetReferrerBeforeOrAtLevel: number;
    levelNeededForBadge: number;
    lifeTimeBadgeMoneySharePercent: number;
    moneyForBeingReferred: number;
  };
  region: {
    battleCooldownHours: number;
    decreaseBy: number;
    decreaseResistanceCost: number;
    depleteHourlyPercent: number;
    increaseBy: number;
    increaseResistanceCost: number;
    maxDailyResistance: number;
    maxResistance: number;
    minDailyResistance: number;
    regionNotLinkedToCapitalMalusDevelopmentPercent: number;
    resistanceAllyBonusPercent: number;
    resistanceBarMultiplier: number;
    resistanceBattleCooldownHours: number;
    resistanceBattleStartCostMultiplier: number;
    resistanceCitizenBonus: number;
    resistanceCitizenBonusPercent: number;
    resistanceContributionCooldownAfterRevoltHours: number;
    resistanceContributionCost: number;
    resistanceContributionMinLevel: number;
    resistanceContributionValue: number;
    resistanceDecayPercent: number;
    resistanceForeignGovCostMultiplier: number;
    resistanceGrowthPercentMax: number;
    resistanceGrowthPercentMin: number;
    resistancePassiveGrowthPercent: number;
    resourcesBonus: {
      "1": number;
      "2": number;
      "3": number;
    };
    transferDaysCooldown: number;
  };
  skills: {
    armor: {
      levels: {
        "0": {
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "1": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "10": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "2": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "3": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "4": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "5": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "6": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "7": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "8": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "9": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
      };
    };
    attack: {
      levels: {
        "0": {
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "1": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "10": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "2": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "3": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "4": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "5": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "6": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "7": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "8": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "9": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
      };
    };
    companies: {
      levels: {
        "0": {
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "1": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "10": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "2": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "3": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "4": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "5": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "6": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "7": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "8": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "9": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
      };
    };
    criticalChance: {
      levels: {
        "0": {
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "1": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "10": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "2": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "3": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "4": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "5": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "6": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "7": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "8": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "9": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
      };
    };
    criticalDamages: {
      levels: {
        "0": {
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "1": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "10": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "2": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "3": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "4": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "5": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "6": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "7": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "8": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "9": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
      };
    };
    dodge: {
      levels: {
        "0": {
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "1": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "10": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "2": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "3": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "4": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "5": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "6": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "7": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "8": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "9": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
      };
    };
    energy: {
      levels: {
        "0": {
          isABar: boolean;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "1": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "10": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "2": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "3": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "4": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "5": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "6": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "7": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "8": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "9": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
      };
    };
    entrepreneurship: {
      levels: {
        "0": {
          isABar: boolean;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "1": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "10": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "2": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "3": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "4": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "5": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "6": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "7": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "8": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "9": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
      };
    };
    health: {
      levels: {
        "0": {
          isABar: boolean;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "1": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "10": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "2": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "3": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "4": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "5": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "6": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "7": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "8": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "9": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
      };
    };
    hunger: {
      levels: {
        "0": {
          isABar: boolean;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "1": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "10": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "2": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "3": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "4": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "5": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "6": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "7": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "8": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "9": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
      };
    };
    lootChance: {
      levels: {
        "0": {
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "1": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "10": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "2": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "3": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "4": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "5": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "6": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "7": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "8": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "9": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
      };
    };
    management: {
      levels: {
        "0": {
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "1": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "10": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "2": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "3": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "4": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "5": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "6": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "7": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "8": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "9": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
      };
    };
    precision: {
      levels: {
        "0": {
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "1": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "10": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "2": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "3": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "4": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "5": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "6": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "7": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "8": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "9": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
      };
    };
    production: {
      levels: {
        "0": {
          isABar: boolean;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "1": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "10": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "2": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "3": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "4": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "5": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "6": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "7": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "8": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
        "9": {
          cost: number;
          totalCost: number;
          unlockAtLevel: number;
          value: number;
        };
      };
    };
  };
  unrest: {
    barMultiplier: number;
    battleCooldownHours: number;
    battleStartCost: number;
    bordersOpenDays: number;
    contributionCooldownAfterRevolutionHours: number;
    contributionCost: number;
    contributionMinLevel: number;
    contributionValue: number;
    nominationPeriodHours: number;
  };
  upgrade: {
    refundPercent: number;
    regionDowngradeCooldownHours: number;
    regionUpgradeCooldownHours: number;
  };
  upgradesConfig: {
    automatedEngine: {
      canDowngrade: boolean;
      levels: {
        "1": {
          constructionPointsCost: number;
          level: number;
          stats: {
            dailyProd: number;
          };
          steelCost: number;
        };
        "2": {
          constructionPointsCost: number;
          level: number;
          stats: {
            dailyProd: number;
          };
          steelCost: number;
        };
        "3": {
          constructionPointsCost: number;
          level: number;
          stats: {
            dailyProd: number;
          };
          steelCost: number;
        };
        "4": {
          constructionPointsCost: number;
          level: number;
          stats: {
            dailyProd: number;
          };
          steelCost: number;
        };
        "5": {
          constructionPointsCost: number;
          level: number;
          stats: {
            dailyProd: number;
          };
          steelCost: number;
        };
        "6": {
          constructionPointsCost: number;
          level: number;
          stats: {
            dailyProd: number;
          };
          steelCost: number;
        };
        "7": {
          constructionPointsCost: number;
          level: number;
          stats: {
            dailyProd: number;
          };
          steelCost: number;
        };
      };
      pendingDurationHours: number;
    };
    base: {
      canBeDestroyed: boolean;
      canBeDisabled: boolean;
      canDowngrade: boolean;
      levels: {
        "1": {
          constructionPointsCost: number;
          level: number;
          maintenanceCostCountryDevScale: number;
          minimumMaintenanceCost: number;
          stats: {
            attackBonus: number;
          };
          steelCost: number;
        };
        "2": {
          constructionPointsCost: number;
          level: number;
          maintenanceCostCountryDevScale: number;
          minimumMaintenanceCost: number;
          stats: {
            attackBonus: number;
          };
          steelCost: number;
        };
        "3": {
          constructionPointsCost: number;
          level: number;
          maintenanceCostCountryDevScale: number;
          minimumMaintenanceCost: number;
          stats: {
            attackBonus: number;
          };
          steelCost: number;
        };
        "4": {
          constructionPointsCost: number;
          level: number;
          maintenanceCostCountryDevScale: number;
          minimumMaintenanceCost: number;
          stats: {
            attackBonus: number;
          };
          steelCost: number;
        };
        "5": {
          constructionPointsCost: number;
          level: number;
          maintenanceCostCountryDevScale: number;
          minimumMaintenanceCost: number;
          stats: {
            attackBonus: number;
          };
          steelCost: number;
        };
      };
      pendingDurationHours: number;
    };
    breakRoom: {
      canDowngrade: boolean;
      levels: {
        "1": {
          level: number;
          stats: {
            dailyHires: number;
            maxWorkers: number;
          };
          steelCost: number;
        };
        "2": {
          level: number;
          stats: {
            dailyHires: number;
            maxWorkers: number;
          };
          steelCost: number;
        };
        "3": {
          level: number;
          stats: {
            dailyHires: number;
            maxWorkers: number;
          };
          steelCost: number;
        };
        "4": {
          level: number;
          stats: {
            dailyHires: number;
            maxWorkers: number;
          };
          steelCost: number;
        };
        "5": {
          level: number;
          stats: {
            dailyHires: number;
            maxWorkers: number;
          };
          steelCost: number;
        };
      };
    };
    bunker: {
      canBeDestroyed: boolean;
      canBeDisabled: boolean;
      canDowngrade: boolean;
      levels: {
        "1": {
          constructionPointsCost: number;
          level: number;
          maintenanceCostCountryDevScale: number;
          minimumMaintenanceCost: number;
          stats: {
            defenseBonus: number;
          };
          steelCost: number;
        };
        "2": {
          constructionPointsCost: number;
          level: number;
          maintenanceCostCountryDevScale: number;
          minimumMaintenanceCost: number;
          stats: {
            defenseBonus: number;
          };
          steelCost: number;
        };
        "3": {
          constructionPointsCost: number;
          level: number;
          maintenanceCostCountryDevScale: number;
          minimumMaintenanceCost: number;
          stats: {
            defenseBonus: number;
          };
          steelCost: number;
        };
        "4": {
          constructionPointsCost: number;
          level: number;
          maintenanceCostCountryDevScale: number;
          minimumMaintenanceCost: number;
          stats: {
            defenseBonus: number;
          };
          steelCost: number;
        };
        "5": {
          constructionPointsCost: number;
          level: number;
          maintenanceCostCountryDevScale: number;
          minimumMaintenanceCost: number;
          stats: {
            defenseBonus: number;
          };
          steelCost: number;
        };
      };
      pendingDurationHours: number;
    };
    dormitories: {
      canDowngrade: boolean;
      levels: {
        "1": {
          level: number;
          stats: {
            members: number;
          };
          steelCost: number;
        };
        "2": {
          level: number;
          stats: {
            members: number;
          };
          steelCost: number;
        };
        "3": {
          level: number;
          stats: {
            members: number;
          };
          steelCost: number;
        };
        "4": {
          level: number;
          stats: {
            members: number;
          };
          steelCost: number;
        };
        "5": {
          level: number;
          stats: {
            members: number;
          };
          steelCost: number;
        };
      };
    };
    headquarters: {
      canBeDisabled: boolean;
      canDowngrade: boolean;
      levels: {
        "1": {
          level: number;
          maintenanceCost: number;
          stats: {
            attackBonus: number;
          };
          steelCost: number;
        };
        "2": {
          level: number;
          maintenanceCost: number;
          stats: {
            attackBonus: number;
          };
          steelCost: number;
        };
        "3": {
          level: number;
          maintenanceCost: number;
          stats: {
            attackBonus: number;
          };
          steelCost: number;
        };
        "4": {
          level: number;
          maintenanceCost: number;
          stats: {
            attackBonus: number;
          };
          steelCost: number;
        };
      };
      pendingDurationHours: number;
    };
    pacificationCenter: {
      canBeDestroyed: boolean;
      canBeDisabled: boolean;
      canDowngrade: boolean;
      levels: {
        "1": {
          constructionPointsCost: number;
          level: number;
          maintenanceCostRegionDevScale: number;
          minimumMaintenanceCost: number;
          stats: {
            resistanceGrowthReduction: number;
          };
          steelCost: number;
        };
        "2": {
          constructionPointsCost: number;
          level: number;
          maintenanceCostRegionDevScale: number;
          minimumMaintenanceCost: number;
          stats: {
            resistanceGrowthReduction: number;
          };
          steelCost: number;
        };
        "3": {
          constructionPointsCost: number;
          level: number;
          maintenanceCostRegionDevScale: number;
          minimumMaintenanceCost: number;
          stats: {
            resistanceGrowthReduction: number;
          };
          steelCost: number;
        };
        "4": {
          constructionPointsCost: number;
          level: number;
          maintenanceCostRegionDevScale: number;
          minimumMaintenanceCost: number;
          stats: {
            resistanceGrowthReduction: number;
          };
          steelCost: number;
        };
        "5": {
          constructionPointsCost: number;
          level: number;
          maintenanceCostRegionDevScale: number;
          minimumMaintenanceCost: number;
          stats: {
            resistanceGrowthReduction: number;
          };
          steelCost: number;
        };
      };
      pendingDurationHours: number;
    };
    storage: {
      canDowngrade: boolean;
      levels: {
        "1": {
          constructionPointsCost: number;
          level: number;
          stats: {
            maxProduction: number;
          };
          steelCost: number;
        };
        "2": {
          constructionPointsCost: number;
          level: number;
          stats: {
            maxProduction: number;
          };
          steelCost: number;
        };
        "3": {
          constructionPointsCost: number;
          level: number;
          stats: {
            maxProduction: number;
          };
          steelCost: number;
        };
        "4": {
          constructionPointsCost: number;
          level: number;
          stats: {
            maxProduction: number;
          };
          steelCost: number;
        };
        "5": {
          constructionPointsCost: number;
          level: number;
          stats: {
            maxProduction: number;
          };
          steelCost: number;
        };
        "6": {
          constructionPointsCost: number;
          level: number;
          stats: {
            maxProduction: number;
          };
          steelCost: number;
        };
        "7": {
          constructionPointsCost: number;
          level: number;
          stats: {
            maxProduction: number;
          };
          steelCost: number;
        };
      };
      pendingDurationHours: number;
    };
  };
  user: {
    activeCitizenMinLevel: number;
    canTakeControlAtLevel: number;
    chatMinLevel: number;
    citizenshipDaysCooldown: number;
    constructionEnergyCost: number;
    dailyReward: {
      case1: number;
      money: number;
      xp: number;
    };
    dailyXp: number;
    donationMinLevel: number;
    energyCostPerAction: number;
    equipmentSets: {
      nonPremiumMax: number;
      premiumMax: number;
    };
    fieldsToPopulate: string;
    isInactiveAfterDays: number;
    marketMinLevel: number;
    maxConstructionPoints: number;
    maxEnergy: number;
    maxHunger: number;
    regenDividedBy: number;
    resetSkillDaysCooldown: number;
    resetSkillsCostPerPoint: number;
    takeControlCooldownInDays: number;
    xpPerAction: number;
  };
  worker: {
    fidelityProductionBonusPercent: number;
    maxFidelity: number;
  };
};

export type GovernmentGetByCountryIdResponse = {
  __v: number;
  _id: string;
  congressMembers: Array<string>;
  country: string;
  minOfDefense: string;
  minOfEconomy: string;
  minOfForeignAffairs: string;
  president: string;
  vicePresident: string;
};

export type ItemTradingGetPricesResponse = {
  ammo: number;
  bread: number;
  case1: number;
  case2: number;
  coca: number;
  cocain: number;
  concrete: number;
  cookedFish: number;
  fish: number;
  grain: number;
  heavyAmmo: number;
  iron: number;
  lead: number;
  lightAmmo: number;
  limestone: number;
  livestock: number;
  oil: number;
  petroleum: number;
  scraps: number;
  steak: number;
  steel: number;
};

export type MuGetByIdResponse = {
  __v: number;
  _id: string;
  activeUpgradeLevels: {
    dormitories: number;
    headquarters: number;
  };
  avatarUrl: string;
  createdAt: string;
  members: Array<string>;
  name: string;
  rankings: {
    muBounty: {
      rank: number;
      tier: string;
      value: number;
    };
    muDamages: {
      rank: number;
      tier: string;
      value: number;
    };
    muTerrain: {
      rank: number;
      tier: string;
      value: number;
    };
    muWealth: {
      rank: number;
      tier: string;
      value: number;
    };
    muWeeklyDamages: {
      rank: number;
      tier: string;
      value: number;
    };
  };
  region: string;
  roles: {
    commanders: Array<string>;
    managers: Array<string>;
  };
  updatedAt: string;
  user: string;
};

export type MuGetManyPaginatedResponse = {
  items: Array<{
    __v: number;
    _id: string;
    activeUpgradeLevels: {
      dormitories: number;
      headquarters?: number;
    };
    avatarUrl: string;
    createdAt: string;
    members: Array<string>;
    name: string;
    rankings: {
      muBounty?: {
        rank: number;
        tier: string;
        value: number;
      };
      muDamages?: {
        rank: number;
        tier: string;
        value: number;
      };
      muTerrain?: {
        rank: number;
        tier: string;
        value: number;
      };
      muWealth: {
        rank: number;
        tier: string;
        value: number;
      };
      muWeeklyDamages?: {
        rank: number;
        tier: string;
        value: number;
      };
    };
    region: string;
    roles: {
      commanders: Array<string>;
      managers: Array<string>;
    };
    updatedAt: string;
    user: string;
  }>;
  nextCursor: string;
};

export type RankingGetRankingResponse = {
  __v: number;
  _id: string;
  isGlobal: boolean;
  items: Array<{
    _id: string;
    country: string;
    rank: number;
    tier: string;
    value: number;
  }>;
  tierValues: {
    bronze: number;
    diamond: number;
    gold: number;
    master: number;
    platinum: number;
    silver: number;
  };
  type: string;
};

export type RegionGetByIdResponse = {
  __v: number;
  _id: string;
  activeUpgradeLevels: {
    bunker: number;
  };
  baseDevelopment: number;
  biome: string;
  climate: string;
  code: string;
  country: string;
  countryCode: string;
  dates: {
    lastOwnershipChangeAt: string;
  };
  development: number;
  initialCountry: string;
  isCapital: boolean;
  isLinkedToCapital: boolean;
  lastBattleEndedAt: string;
  lastResistanceContributionAt: string;
  lastRevoltEndedAt: string;
  mainCity: string;
  name: string;
  neighbors: Array<string>;
  position: Array<number>;
  resistance: number;
  resistanceMax: number;
  stats: {
    investedMoney: number;
  };
  upgradesV2: {
    upgrades: {};
  };
};

export type RegionGetRegionsObjectResponse = Record<string, {
    __v: number;
    _id: string;
    activeBattle?: {
      __v: number;
      _id: string;
      attacker: {
        country: string;
        countryOrders: Array<string>;
        damages: number;
        hitCount: number;
        moneyPer1kDamages?: number;
        moneyPool?: number;
        muOrders: Array<string>;
        region?: string;
        wonRoundsCount: number;
      };
      createdAt: string;
      currentRound: string;
      defender: {
        country: string;
        countryOrders: Array<string>;
        damages: number;
        hitCount: number;
        moneyPer1kDamages?: number;
        moneyPool?: number;
        muOrders: Array<string>;
        region: string;
        wonRoundsCount: number;
      };
      isActive: boolean;
      isBigBattle?: boolean;
      rounds: Array<string>;
      roundsHistory: Array<string>;
      roundsToWin: number;
      stats: {
        hitCount: number;
      };
      type: string;
      updatedAt: string;
      war: string;
    };
    activeUpgradeLevels?: {
      base?: number;
      bunker?: number;
      pacificationCenter?: number;
    };
    baseDevelopment: number;
    biome: string;
    climate: string;
    code: string;
    country: string;
    countryCode: string;
    dates: {
      lastOwnershipChangeAt?: string;
    };
    deposit?: {
      bonusPercent: number;
      endsAt: string;
      startsAt: string;
      type: string;
    };
    development: number;
    hasCoast?: boolean;
    initialCountry: string;
    isCapital: boolean;
    isLinkedToCapital: boolean;
    lastBattleEndedAt?: string;
    lastResistanceContributionAt?: string;
    lastRevoltEndedAt?: string;
    mainCity: string;
    name: string;
    neighbors: Array<string>;
    position: Array<number>;
    resistance: number;
    resistanceMax: number;
    stats: {
      investedMoney: number;
    };
    strategicResource?: string;
    upgradesV2: {
      activeConstructionCount?: number;
      upgrades: {
        base?: {
          constructionEndedAt: string;
          constructionPoints: number;
          constructionStartedAt: string;
          investedMoney: number;
          isUnderConstruction: unknown;
          lastConstructions: unknown[];
          level: number;
          status: string;
          statusChangedAt?: string;
        };
        bunker?: {
          constructionEndedAt?: string;
          constructionPoints: number;
          constructionStartedAt: string;
          investedMoney: number;
          isUnderConstruction: unknown;
          lastConstructions: Array<{
            construction: number;
            constructionAt: string;
            user: string;
          }>;
          level: number;
          status?: string;
          statusChangedAt?: string;
        };
      };
    };
  }>;

export type RoundGetByIdResponse = {
  __v: number;
  _id: string;
  attacker: {
    country: string;
    damages: number;
    hitCount: number;
    lastHits: Array<{
      _id: string;
      ammo: unknown;
      damages: number;
      equipments: Array<{
        _id: string;
        code: string;
        lastAcquisitionAt: string;
        maxState: number;
        quantity: number;
        skills: {
          armor?: number;
          criticalDamages?: number;
          dodge?: number;
          precision?: number;
        };
        state: number;
        type: string;
      }>;
      hitAt: string;
      isCriticalHit: boolean;
      isMissed: boolean;
      mu: unknown;
      user: string;
      weapon: {
        _id: string;
        code: string;
        lastAcquisitionAt: string;
        maxState: number;
        quantity: number;
        skills: {
          attack: number;
          criticalChance: number;
        };
        state: number;
      };
    }>;
    points: number;
  };
  battle: string;
  createdAt: string;
  defender: {
    country: string;
    damages: number;
    hitCount: number;
    lastHits: Array<{
      _id: string;
      ammo: string;
      damages: number;
      equipments: Array<{
        _id: string;
        code: string;
        lastAcquisitionAt: string;
        maxState: number;
        quantity: number;
        skills: {
          armor?: number;
          criticalDamages?: number;
          dodge?: number;
          precision?: number;
        };
        state: number;
        type: string;
      }>;
      hitAt: string;
      isCriticalHit: boolean;
      isMissed: boolean;
      mu: string;
      user: string;
      weapon: {
        _id: string;
        code: string;
        lastAcquisitionAt: string;
        maxState: number;
        quantity: number;
        skills: {
          attack: number;
          criticalChance: number;
        };
        state: number;
      };
    }>;
    points: number;
  };
  isActive: boolean;
  live: {
    actualTickPoints: number;
    nextTickAt: string;
    ticksCount: number;
  };
  number: number;
  updatedAt: string;
};

export type RoundGetLastHitsResponse = {
  attacker: Array<{
    _id: string;
    ammo: unknown;
    damages: number;
    equipments: Array<{
      _id: string;
      code: string;
      lastAcquisitionAt: string;
      maxState: number;
      quantity: number;
      skills: {
        armor?: number;
        criticalDamages?: number;
        dodge?: number;
        precision?: number;
      };
      state: number;
      type: string;
    }>;
    hitAt: string;
    isCriticalHit: boolean;
    isMissed: boolean;
    mu: unknown;
    user: string;
    weapon: {
      _id: string;
      code: string;
      lastAcquisitionAt: string;
      maxState: number;
      quantity: number;
      skills: {
        attack: number;
        criticalChance: number;
      };
      state: number;
    };
  }>;
  defender: Array<{
    _id: string;
    ammo: string;
    damages: number;
    equipments: Array<{
      _id: string;
      code: string;
      lastAcquisitionAt: string;
      maxState: number;
      quantity: number;
      skills: {
        armor?: number;
        criticalDamages?: number;
        dodge?: number;
        precision?: number;
      };
      state: number;
      type: string;
    }>;
    hitAt: string;
    isCriticalHit: boolean;
    isMissed: boolean;
    mu: string;
    user: string;
    weapon: {
      _id: string;
      code: string;
      lastAcquisitionAt: string;
      maxState: number;
      quantity: number;
      skills: {
        attack: number;
        criticalChance: number;
      };
      state: number;
    };
  }>;
};

export type SearchSearchAnythingResponse = {
  countryIds: unknown[];
  hasData: boolean;
  muIds: Array<string>;
  partyIds: unknown[];
  regionIds: unknown[];
  userIds: Array<string>;
};

export type TradingOrderGetTopOrdersResponse = {
  buyOrders: Array<{
    __v: number;
    _id: string;
    itemCode: string;
    offerAt: string;
    price: number;
    quantity: number;
    type: string;
    user: string;
  }>;
  sellOrders: Array<{
    __v: number;
    _id: string;
    country?: string;
    itemCode: string;
    offerAt: string;
    price: number;
    quantity: number;
    type: string;
    user: string;
  }>;
};

export type TransactionGetPaginatedTransactionsResponse = {
  items: Array<{
    __v: number;
    _id: string;
    buyerId: string;
    createdAt: string;
    item?: {
      _id: string;
      code: string;
      lastAcquisitionAt: string;
      maxState: number;
      quantity: number;
      skills: {
        attack?: number;
        criticalChance?: number;
        criticalDamages?: number;
        dodge?: number;
      };
      state: number;
      type?: string;
    };
    itemCode?: string;
    money?: number;
    offerCreatedAt?: string;
    quantity: number;
    sellerId: string;
    transactionType: string;
    updatedAt: string;
  }>;
  nextCursor: string;
};

export type UpgradeGetUpgradeByTypeAndEntityResponse = {
  __v: number;
  _id: string;
  createdAt: string;
  dependantUsersCount: number;
  investedConcrete: number;
  investedMoney: number;
  investedSteel: number;
  level: number;
  region: string;
  status: string;
  statusChangedAt: string;
  updatedAt: string;
  upgradeType: string;
  willBeActiveAt: string;
};

export type UserGetUserLiteResponse = {
  _id: string;
  avatarUrl: string;
  country: string;
  createdAt: string;
  dates: {
    lastCompanyJoinedAt: string;
    lastConnectionAt: string;
    lastCountryMessageCheckAt: string;
    lastDailyRewardClaimedAt: string;
    lastEventsCheckAt: string;
    lastGlobalMessageCheckAt: string;
    lastHelpAskedAt: string;
    lastHiresAt: Array<string>;
    lastNotificationsCheckAt: string;
    lastWorkAt: string;
    lastWorkOfferApplications: Array<string>;
  };
  infos: {
    congressMemberOf: string;
    minOfEconomyOf: string;
  };
  isActive: boolean;
  leveling: {
    availableSkillPoints: number;
    dailyXpLeft: number;
    freeReset: number;
    level: number;
    spentSkillPoints: number;
    totalSkillPoints: number;
    totalXp: number;
  };
  militaryRank: number;
  mu: string;
  rankings: {
    userBounty: {
      rank: number;
      tier: string;
      value: number;
    };
    userCasesOpened: {
      rank: number;
      tier: string;
      value: number;
    };
    userDamages: {
      rank: number;
      tier: string;
      value: number;
    };
    userGemsPurchased: {
      rank: number;
      tier: string;
      value: number;
    };
    userLevel: {
      rank: number;
      tier: string;
      value: number;
    };
    userReferrals: {
      rank: number;
      tier: string;
      value: number;
    };
    userSubscribers: {
      rank: number;
      tier: string;
      value: number;
    };
    userWealth: {
      rank: number;
      tier: string;
      value: number;
    };
    weeklyUserDamages: {
      rank: number;
      tier: string;
      value: number;
    };
  };
  skills: {
    armor: {
      equipment: number;
      level: number;
      limited: unknown;
      total: number;
      totalAfterSoftCap: unknown;
      value: number;
      weapon: unknown;
    };
    attack: {
      ammoPercent: number;
      buffsPercent: number;
      debuffsPercent: number;
      equipment: unknown;
      level: number;
      limited: unknown;
      militaryRankPercent: number;
      total: number;
      totalAfterSoftCap: unknown;
      value: number;
      weapon: number;
    };
    companies: {
      equipment: unknown;
      level: number;
      limited: unknown;
      total: number;
      totalAfterSoftCap: unknown;
      value: number;
      weapon: unknown;
    };
    criticalChance: {
      equipment: unknown;
      level: number;
      limited: unknown;
      total: number;
      totalAfterSoftCap: unknown;
      value: number;
      weapon: number;
    };
    criticalDamages: {
      equipment: number;
      level: number;
      limited: unknown;
      total: number;
      totalAfterSoftCap: unknown;
      value: number;
      weapon: unknown;
    };
    dodge: {
      equipment: number;
      level: number;
      limited: unknown;
      total: number;
      totalAfterSoftCap: unknown;
      value: number;
      weapon: unknown;
    };
    energy: {
      currentBarValue: number;
      equipment: unknown;
      hourlyBarRegen: number;
      level: number;
      limited: unknown;
      total: number;
      totalAfterSoftCap: unknown;
      value: number;
      weapon: unknown;
    };
    entrepreneurship: {
      currentBarValue: number;
      equipment: unknown;
      hourlyBarRegen: number;
      level: number;
      limited: unknown;
      total: number;
      totalAfterSoftCap: unknown;
      value: number;
      weapon: unknown;
    };
    health: {
      currentBarValue: number;
      equipment: unknown;
      hourlyBarRegen: number;
      level: number;
      limited: unknown;
      total: number;
      totalAfterSoftCap: unknown;
      value: number;
      weapon: unknown;
    };
    hunger: {
      currentBarValue: number;
      equipment: unknown;
      hourlyBarRegen: number;
      level: number;
      limited: unknown;
      total: number;
      totalAfterSoftCap: unknown;
      value: number;
      weapon: unknown;
    };
    lootChance: {
      equipment: unknown;
      level: number;
      limited: unknown;
      total: number;
      totalAfterSoftCap: unknown;
      value: number;
      weapon: unknown;
    };
    management: {
      equipment: unknown;
      level: number;
      limited: unknown;
      total: number;
      totalAfterSoftCap: unknown;
      value: number;
      weapon: unknown;
    };
    precision: {
      equipment: number;
      level: number;
      limited: unknown;
      total: number;
      totalAfterSoftCap: unknown;
      value: number;
      weapon: unknown;
    };
    production: {
      currentBarValue: number;
      equipment: unknown;
      hourlyBarRegen: number;
      level: number;
      limited: unknown;
      total: number;
      totalAfterSoftCap: unknown;
      value: number;
      weapon: unknown;
    };
  };
  stats: {
    damagesCount: number;
  };
  username: string;
};

export type UserGetUsersByCountryResponse = {
  items: Array<{
    _id: string;
    createdAt: string;
  }>;
  nextCursor: string;
};

export type WorkerGetTotalWorkersCountResponse = number;

export type WorkerGetWorkersResponse = {
  type: string;
  workers?: Array<{
    __v: number;
    _id: string;
    company: string;
    createdAt: string;
    employer: string;
    fidelity: number;
    joinedAt: string;
    lastFidelityIncreaseAt: string;
    lastWageReductionAcceptationAt?: string;
    lastWageReductionAt?: string;
    lockedUntil?: string;
    previousWage?: number;
    updatedAt: string;
    user: string;
    wage: number;
  }>;
  workersPerCompany?: Array<{
    company: {
      _id: string;
      itemCode: string;
      name: string;
    };
    workers: unknown[];
  }>;
};

export type WorkOfferGetByIdResponse = {
  __v: number;
  _id: string;
  company: string;
  createdAt: string;
  initialQuantity: number;
  minEnergy: number;
  minProduction: number;
  quantity: number;
  region: string;
  updatedAt: string;
  user: string;
  wage: number;
};

export type WorkOfferGetWorkOfferByCompanyIdResponse = {
  __v: number;
  _id: string;
  company: string;
  createdAt: string;
  initialQuantity: number;
  minEnergy: number;
  minProduction: number;
  quantity: number;
  region: string;
  text: string;
  updatedAt: string;
  user: string;
  wage: number;
};

export type WorkOfferGetWorkOffersPaginatedResponse = {
  items: Array<{
    __v: number;
    _id: string;
    company: string;
    createdAt: string;
    initialQuantity: number;
    minEnergy?: number;
    minProduction: number;
    quantity: number;
    region: string;
    text?: string;
    updatedAt: string;
    user: string;
    wage: number;
  }>;
  nextCursor: string;
};

export interface Responses {
  "article.getArticleById": ArticleGetArticleByIdResponse;
  "article.getArticleLiteById": ArticleGetArticleLiteByIdResponse;
  "article.getArticlesPaginated": ArticleGetArticlesPaginatedResponse;
  "battle.getBattles": BattleGetBattlesResponse;
  "battle.getById": BattleGetByIdResponse;
  "battle.getLiveBattleData": BattleGetLiveBattleDataResponse;
  "battleRanking.getRanking": BattleRankingGetRankingResponse;
  "company.getById": CompanyGetByIdResponse;
  "company.getCompanies": CompanyGetCompaniesResponse;
  "country.getAllCountries": CountryGetAllCountriesResponse;
  "country.getCountryById": CountryGetCountryByIdResponse;
  "event.getEventsPaginated": EventGetEventsPaginatedResponse;
  "gameConfig.getDates": GameConfigGetDatesResponse;
  "gameConfig.getGameConfig": GameConfigGetGameConfigResponse;
  "government.getByCountryId": GovernmentGetByCountryIdResponse;
  "itemTrading.getPrices": ItemTradingGetPricesResponse;
  "mu.getById": MuGetByIdResponse;
  "mu.getManyPaginated": MuGetManyPaginatedResponse;
  "ranking.getRanking": RankingGetRankingResponse;
  "region.getById": RegionGetByIdResponse;
  "region.getRegionsObject": RegionGetRegionsObjectResponse;
  "round.getById": RoundGetByIdResponse;
  "round.getLastHits": RoundGetLastHitsResponse;
  "search.searchAnything": SearchSearchAnythingResponse;
  "tradingOrder.getTopOrders": TradingOrderGetTopOrdersResponse;
  "transaction.getPaginatedTransactions": TransactionGetPaginatedTransactionsResponse;
  "upgrade.getUpgradeByTypeAndEntity": UpgradeGetUpgradeByTypeAndEntityResponse;
  "user.getUserLite": UserGetUserLiteResponse;
  "user.getUsersByCountry": UserGetUsersByCountryResponse;
  "worker.getTotalWorkersCount": WorkerGetTotalWorkersCountResponse;
  "worker.getWorkers": WorkerGetWorkersResponse;
  "workOffer.getById": WorkOfferGetByIdResponse;
  "workOffer.getWorkOfferByCompanyId": WorkOfferGetWorkOfferByCompanyIdResponse;
  "workOffer.getWorkOffersPaginated": WorkOfferGetWorkOffersPaginatedResponse;
}
