// Generated by Responses/convert_to_types.ts

export interface ArticleStats {
  comments: number;
  dislikes: number;
  gemTips: number;
  likes: number;
  score: number;
  subs: number;
  tips: number;
  views: number;
}

export interface ArticleListItem {
  __v: number;
  _id: string;
  author: string;
  category: string;
  content: string;
  createdAt: string;
  isDeleted: boolean;
  isPublished: boolean;
  language: string;
  publishedAt: string;
  stats: ArticleStats;
  title: string;
  updatedAt: string;
}

export interface BattleSideSummary {
  country: string;
  countryOrders: Array<string>;
  damages: number;
  hitCount: number;
  moneyPer1kDamages?: number;
  moneyPool?: number;
  muOrders: Array<string>;
  region?: string;
  wonRoundsCount: number;
}

export interface EquipmentSkillsDefensive {
  armor?: number;
  criticalDamages?: number;
  dodge?: number;
  precision?: number;
}

export interface RoundEquipment {
  _id: string;
  code: string;
  lastAcquisitionAt: string;
  maxState: number;
  quantity: number;
  skills: EquipmentSkillsDefensive;
  state: number;
  type: string;
}

export interface WeaponSkills {
  attack: number;
  criticalChance: number;
}

export interface RoundWeapon {
  _id: string;
  code: string;
  lastAcquisitionAt: string;
  maxState: number;
  quantity: number;
  skills: WeaponSkills;
  state: number;
}

export interface RoundLastHit {
  _id: string;
  ammo?: string;
  damages: number;
  equipments: Array<RoundEquipment>;
  hitAt: string;
  isCriticalHit: boolean;
  isMissed: boolean;
  mu?: string;
  user: string;
  weapon?: RoundWeapon;
}

export interface RoundSideCombatStats {
  country: string;
  damages: number;
  hitCount: number;
  lastHits: Array<RoundLastHit>;
  points: number;
}

export interface RoundSideCombatStatsOptionalHitCount {
  country: string;
  damages: number;
  hitCount?: number;
  lastHits: Array<RoundLastHit>;
  points: number;
}

export interface RoundLiveState {
  actualTickPoints: number;
  nextTickAt: string;
  ticksCount: number;
}

export interface BattleCurrentRound {
  __v: number;
  _id: string;
  attacker: RoundSideCombatStats;
  battle: string;
  createdAt: string;
  defender: RoundSideCombatStatsOptionalHitCount;
  isActive: boolean;
  live: RoundLiveState;
  number: number;
  updatedAt: string;
}

export interface BattleDefenderSummary {
  country: string;
  countryOrders: Array<string>;
  damages: number;
  hitCount: number;
  moneyPer1kDamages?: number;
  moneyPool?: number;
  muOrders: Array<string>;
  region: string;
  wonRoundsCount: number;
}

export interface BattleStats {
  hitCount: number;
}

export interface BattleListItem {
  __v: number;
  _id: string;
  attacker: BattleSideSummary;
  createdAt: string;
  currentRound: BattleCurrentRound;
  defender: BattleDefenderSummary;
  isActive: boolean;
  rounds: Array<string>;
  roundsHistory: unknown[];
  roundsToWin: number;
  stats: BattleStats;
  type: string;
  updatedAt: string;
  war: string;
}

export interface BattleDetailedSide {
  country: string;
  countryOrders: unknown[];
  damages: number;
  hitCount: number;
  muOrders: unknown[];
  region: string;
  wonRoundsCount: number;
}

export interface LiveBattleSummary {
  attackerCountryOrders: unknown[];
  defenderCountryOrders: unknown[];
  isActive: boolean;
  roundHistory: Array<string>;
  roundIds: Array<string>;
}

export interface LiveRoundSummary {
  actualTickPoints: number;
  attackerDamages: number;
  attackerPoints: number;
  defenderDamages: number;
  defenderPoints: number;
  isActive: boolean;
  nextTickAt: string;
  roundId: string;
}

export interface CompanyActiveUpgradeLevels {
  automatedEngine: number;
  breakRoom: number;
  storage: number;
}

export interface CompanyDates {
  lastHiresAt: Array<string>;
}

export interface RankingValueTier {
  rank: number;
  tier: string;
  value: number;
}

export interface CountryRankingsOptionalCitizenDamage {
  countryActivePopulation: RankingValueTier;
  countryBounty: RankingValueTier;
  countryDamages: RankingValueTier;
  countryDevelopment: RankingValueTier;
  countryProductionBonus: RankingValueTier;
  countryRegionDiff: RankingValueTier;
  countryWealth: RankingValueTier;
  weeklyCountryDamages: RankingValueTier;
  weeklyCountryDamagesPerCitizen?: RankingValueTier;
}

export interface CountryResourceBonuses {
  developmentPercent: number;
  productionPercent: number;
}

export interface CountryStrategicResources {
  coal?: Array<string>;
  diamonds?: Array<string>;
  gold?: Array<string>;
  lithium?: Array<string>;
  rareEarths?: Array<string>;
  uranium?: Array<string>;
}

export interface CountryStrategicResourceConfig {
  bonuses: CountryResourceBonuses;
  resources: CountryStrategicResources;
}

export interface CountryTaxes {
  income: number;
  market: number;
  selfWork: number;
}

export interface CountryUnrestOptionalContributionDate {
  bar: number;
  barMax: number;
  lastContributionAt?: string;
}

export interface CountryListItem {
  __v: number;
  _id: string;
  allies: Array<string>;
  code: string;
  createdAt?: string;
  currentBattleOrder?: string;
  development: number;
  discordUrl?: string;
  enemy?: string;
  mapAccent: string;
  money: number;
  name: string;
  orgs: Array<string>;
  pinnedArticle?: string;
  rankings: CountryRankingsOptionalCitizenDamage;
  rulingParty?: string;
  scheme: string;
  specializedItem?: string;
  strategicResources?: CountryStrategicResourceConfig;
  taxes: CountryTaxes;
  unrest: CountryUnrestOptionalContributionDate;
  updatedAt: string;
  warsWith: Array<string>;
}

export interface CountryRankings {
  countryActivePopulation: RankingValueTier;
  countryBounty: RankingValueTier;
  countryDamages: RankingValueTier;
  countryDevelopment: RankingValueTier;
  countryProductionBonus: RankingValueTier;
  countryRegionDiff: RankingValueTier;
  countryWealth: RankingValueTier;
  weeklyCountryDamages: RankingValueTier;
  weeklyCountryDamagesPerCitizen: RankingValueTier;
}

export interface CountryStrategicResourcesGoldOnly {
  gold: Array<string>;
}

export interface CountryStrategicResourceConfigGoldOnly {
  bonuses: CountryResourceBonuses;
  resources: CountryStrategicResourcesGoldOnly;
}

export interface CountryUnrest {
  bar: number;
  barMax: number;
  lastContributionAt: string;
}

export interface EventData {
  amount?: number;
  attackerCountry?: string;
  attackerRegion?: string;
  battle?: string;
  bonusPercent?: number;
  countries?: Array<string>;
  defenderCountry?: string;
  defenderRegion?: string;
  money?: number;
  regions?: Array<string>;
  type: string;
  war?: string;
  wars?: Array<string>;
  wonBy?: string;
}

export interface EventListItem {
  __v: number;
  _id: string;
  countries: Array<string>;
  createdAt: string;
  data: EventData;
  priority: string;
  updatedAt: string;
}

export interface BadgeRewardWithPreserve {
  preserveBetweenReset: boolean;
  reward: number;
}

export interface BadgeReward {
  reward: number;
}

export interface BadgeRewardWithMetadata {
  preserveBetweenReset: boolean;
  reward: number;
  uniqueMetadataKey: string;
}

export interface GameConfigBadges {
  alphaTester: BadgeRewardWithPreserve;
  babyBoomer: BadgeRewardWithPreserve;
  battleTerrainTop1: BadgeReward;
  battleTop1: BadgeReward;
  bugFinder: BadgeRewardWithPreserve;
  coffee: BadgeRewardWithPreserve;
  congressMember: BadgeReward;
  countryPresident: BadgeReward;
  countryTournamentWinner: BadgeRewardWithPreserve;
  foundingFather: BadgeRewardWithPreserve;
  giftPremium: BadgeRewardWithPreserve;
  giveawayWinner: BadgeReward;
  hardWorker: BadgeReward;
  muTournamentWinner: BadgeRewardWithPreserve;
  popularArticle: BadgeRewardWithMetadata;
  premium: BadgeRewardWithPreserve;
  referral: BadgeReward;
  resetSurvivor: BadgeRewardWithPreserve;
  roundTerrainTop1: BadgeReward;
  roundTop1: BadgeReward;
  staff: BadgeRewardWithPreserve;
  sugarDaddy: BadgeRewardWithPreserve;
  translator: BadgeRewardWithPreserve;
  vicePresident: BadgeReward;
  voted: BadgeReward;
}

export interface BattleTickPoints {
  "1": number;
  "100": number;
  "200": number;
  "300": number;
  "400": number;
  "500": number;
}

export interface GameConfigBattle {
  allianceDamagesBonusPercent: number;
  casesPer1kDamagesInPool: number;
  countryOrderBonusPercent: number;
  enemyDamagesBonusPercent: number;
  healthCost: number;
  hitFor1CaseInPool: number;
  lostAttackingRegionMalusPercent: number;
  maxRounds: number;
  muOrderBonusPercent: number;
  occupyingYourRegionsMalusPercent: number;
  patrioticBonusPercent: number;
  pointsToWinRound: number;
  regionNotLinkedToCapitalMalusPercent: number;
  roundsToWin: number;
  setCountryOrderMoneyCost: number;
  setMuOrderMoneyCost: number;
  setOrderMoneyCost: number;
  tickPoints: BattleTickPoints;
}

export interface GameConfigCitizenshipApplication {
  autoApprovalEnabled: boolean;
  autoApprovalMaxPopulation: number;
}

export interface GameConfigCompany {
  changeItemCost: number;
  constructionCostIncreasePerCompany: number;
  depositResourceBonus: number;
  destructionValuePercent: number;
  moveCost: number;
}

export interface GameConfigCountry {
  hijackedTaxPercentPerResistance: number;
  maxTaxAmount: number;
}

export interface GameConfigElection {
  candidateDurationHours: number;
  candidateMinLevel: number;
  electionVoteDurationHours: number;
  voteMinLevel: number;
}

export interface GameConfigGovernment {
  resistanceDecreasedCooldownInHours: number;
  resistanceIncreasedCooldownInHours: number;
}

export interface ItemFlatStatsPercentAttack {
  percentAttack: number;
}

export interface ItemProductionNeedsLead {
  lead: number;
}

export interface ItemAmmo {
  code: string;
  flatStats: ItemFlatStatsPercentAttack;
  isTradable: boolean;
  productionNeeds: ItemProductionNeedsLead;
  productionPoints: number;
  rarity: string;
  skinSlot: string;
  type: string;
  usage: string;
}

export interface ItemDynamicStatsDodge {
  dodge: Array<number>;
}

export interface ItemBoots {
  code: string;
  dynamicStats: ItemDynamicStatsDodge;
  iconImg: string;
  rarity: string;
  skinSlot: string;
  type: string;
  usage: string;
}

export interface ItemFlatStatsHealthRegen {
  healthRegen: number;
}

export interface ItemIconComponent {
  compare?: unknown;
}

export interface ItemProductionNeedsGrain {
  grain: number;
}

export interface ItemBread {
  code: string;
  flatStats: ItemFlatStatsHealthRegen;
  IconComponent: ItemIconComponent;
  isConsumable: boolean;
  isTradable: boolean;
  productionNeeds: ItemProductionNeedsGrain;
  productionPoints: number;
  rarity: string;
  type: string;
}

export interface ItemCase {
  code: string;
  isTradable: boolean;
  rarity: string;
  type: string;
  usage: string;
}

export interface ItemDynamicStatsArmor {
  armor: Array<number>;
}

export interface ItemChestOrPants {
  code: string;
  dynamicStats: ItemDynamicStatsArmor;
  iconImg: string;
  rarity: string;
  skinSlot: string;
  type: string;
  usage: string;
}

export interface ItemDepositResource {
  climates: Array<string>;
  code: string;
  IconComponent: ItemIconComponent;
  isDeposit: boolean;
  isTradable: boolean;
  productionPoints: number;
  rarity: string;
  type: string;
}

export interface ItemFlatStatsCocain {
  buffDurationHours: number;
  debuffDurationHours: number;
  percentAttack: number;
}

export interface ItemProductionNeedsCoca {
  coca: number;
}

export interface ItemCocain {
  code: string;
  flatStats: ItemFlatStatsCocain;
  IconComponent: ItemIconComponent;
  isTradable: boolean;
  productionNeeds: ItemProductionNeedsCoca;
  productionPoints: number;
  rarity: string;
  type: string;
}

export interface ItemProductionNeedsLimestone {
  limestone: number;
}

export interface ItemConcrete {
  code: string;
  isTradable: boolean;
  productionNeeds: ItemProductionNeedsLimestone;
  productionPoints: number;
  rarity: string;
  type: string;
}

export interface ItemProductionNeedsFish {
  fish: number;
}

export interface ItemCookedFish {
  code: string;
  flatStats: ItemFlatStatsHealthRegen;
  isConsumable: boolean;
  isTradable: boolean;
  productionNeeds: ItemProductionNeedsFish;
  productionPoints: number;
  rarity: string;
  type: string;
}

export interface ItemDynamicStatsPrecision {
  precision: Array<number>;
}

export interface ItemGloves {
  code: string;
  dynamicStats: ItemDynamicStatsPrecision;
  iconImg: string;
  rarity: string;
  skinSlot: string;
  type: string;
  usage: string;
}

export interface ItemDynamicStatsWeaponBase {
  attack: Array<number>;
  criticalChance: Array<number>;
}

export interface ItemWeaponMeleeOrHeavy {
  code: string;
  dynamicStats: ItemDynamicStatsWeaponBase;
  IconComponent: ItemIconComponent;
  rarity: string;
  skinSlot: string;
  type: string;
  usage: string;
}

export interface ItemHeavyAmmo {
  code: string;
  flatStats: ItemFlatStatsPercentAttack;
  IconComponent: ItemIconComponent;
  isTradable: boolean;
  productionNeeds: ItemProductionNeedsLead;
  productionPoints: number;
  rarity: string;
  skinSlot: string;
  type: string;
  usage: string;
}

export interface ItemDynamicStatsCriticalDamages {
  criticalDamages: Array<number>;
}

export interface ItemHelmet {
  code: string;
  dynamicStats: ItemDynamicStatsCriticalDamages;
  iconImg: string;
  rarity: string;
  skinSlot: string;
  type: string;
  usage: string;
}

export interface ItemRawResource {
  climates: Array<string>;
  code: string;
  isDeposit: boolean;
  isTradable: boolean;
  productionPoints: number;
  rarity: string;
  type: string;
}

export interface ItemRifleLike {
  code: string;
  dynamicStats: ItemDynamicStatsWeaponBase;
  rarity: string;
  skinSlot: string;
  type: string;
  usage: string;
}

export interface ItemProductionNeedsPetroleum {
  petroleum: number;
}

export interface ItemOil {
  code: string;
  IconComponent: ItemIconComponent;
  isTradable: boolean;
  productionNeeds: ItemProductionNeedsPetroleum;
  productionPoints: number;
  rarity: string;
  type: string;
}

export interface ItemScraps {
  code: string;
  isTradable: boolean;
  rarity: string;
  type: string;
}

export interface ItemProductionNeedsLivestock {
  livestock: number;
}

export interface ItemSteak {
  code: string;
  flatStats: ItemFlatStatsHealthRegen;
  IconComponent: ItemIconComponent;
  isConsumable: boolean;
  isTradable: boolean;
  productionNeeds: ItemProductionNeedsLivestock;
  productionPoints: number;
  rarity: string;
  type: string;
}

export interface ItemProductionNeedsIron {
  iron: number;
}

export interface ItemSteel {
  code: string;
  isTradable: boolean;
  productionNeeds: ItemProductionNeedsIron;
  productionPoints: number;
  rarity: string;
  type: string;
}

export interface GameConfigItems {
  ammo: ItemAmmo;
  boots1: ItemBoots;
  boots2: ItemBoots;
  boots3: ItemBoots;
  boots4: ItemBoots;
  boots5: ItemBoots;
  boots6: ItemBoots;
  bread: ItemBread;
  case1: ItemCase;
  case2: ItemCase;
  chest1: ItemChestOrPants;
  chest2: ItemChestOrPants;
  chest3: ItemChestOrPants;
  chest4: ItemChestOrPants;
  chest5: ItemChestOrPants;
  chest6: ItemChestOrPants;
  coca: ItemDepositResource;
  cocain: ItemCocain;
  concrete: ItemConcrete;
  cookedFish: ItemCookedFish;
  fish: ItemDepositResource;
  gloves1: ItemGloves;
  gloves2: ItemGloves;
  gloves3: ItemGloves;
  gloves4: ItemGloves;
  gloves5: ItemGloves;
  gloves6: ItemGloves;
  grain: ItemDepositResource;
  gun: ItemWeaponMeleeOrHeavy;
  heavyAmmo: ItemHeavyAmmo;
  helmet1: ItemHelmet;
  helmet2: ItemHelmet;
  helmet3: ItemHelmet;
  helmet4: ItemHelmet;
  helmet5: ItemHelmet;
  helmet6: ItemHelmet;
  iron: ItemRawResource;
  jet: ItemRifleLike;
  knife: ItemWeaponMeleeOrHeavy;
  lead: ItemRawResource;
  lightAmmo: ItemAmmo;
  limestone: ItemRawResource;
  livestock: ItemDepositResource;
  oil: ItemOil;
  pants1: ItemChestOrPants;
  pants2: ItemChestOrPants;
  pants3: ItemChestOrPants;
  pants4: ItemChestOrPants;
  pants5: ItemChestOrPants;
  pants6: ItemChestOrPants;
  petroleum: ItemDepositResource;
  rifle: ItemRifleLike;
  scraps: ItemScraps;
  sniper: ItemRifleLike;
  steak: ItemSteak;
  steel: ItemSteel;
  tank: ItemWeaponMeleeOrHeavy;
}

export interface LawActionCostAndMaintenance {
  cost: number;
  maintenanceCost: number;
}

export interface LawActionCost {
  cost: number;
}

export interface GameConfigLaw {
  abusiveLawPossibleVotersNeeded: number;
  abusiveLawsCooldownInDays: number;
  accept_alliance: LawActionCostAndMaintenance;
  define_enemy_country: LawActionCostAndMaintenance;
  lawVotesDurationHours: number;
  propose_alliance: LawActionCostAndMaintenance;
  set_color_scheme: LawActionCost;
  votersRatioNeeded: number;
}

export interface MergingCostByRarity {
  common: number;
  epic: number;
  legendary: number;
  mythic: number;
  rare: number;
  uncommon: number;
}

export interface MissionRerollCostByLevel {
  "0": number;
  "1": number;
  "10": number;
  "11": number;
  "12": number;
  "13": number;
  "14": number;
  "15": number;
  "16": number;
  "17": number;
  "18": number;
  "19": number;
  "2": number;
  "20": number;
  "3": number;
  "4": number;
  "5": number;
  "6": number;
  "7": number;
  "8": number;
  "9": number;
}

export interface MissionRewardConfig {
  cases: number;
  money: number;
  xp: number;
  xpWhenFinished: number;
}

export interface MissionRewardByPeriod {
  daily: MissionRewardConfig;
  monthly: MissionRewardConfig;
  starting: MissionRewardConfig;
  weekly: MissionRewardConfig;
}

export interface GameConfigMission {
  rerollMissionCost: MissionRerollCostByLevel;
  reward: MissionRewardByPeriod;
}

export interface GameConfigMu {
  constructionCost: number;
  destructionValuePercent: number;
  healthPerHelp: number;
  helpCooldownHours: number;
  helpValue: number;
  maxOwnedMus: number;
  moveCost: number;
}

export interface GameConfigNewspaper {
  createArticleMinLevel: number;
  gemTipValue: number;
  publishCost: number;
  tipMinLevel: number;
  tipValue: number;
}

export interface GameConfigOrg {
  constructionCost: number;
  moveCost: number;
}

export interface GameConfigParty {
  createCost: number;
}

export interface GameConfigReferral {
  canSetReferrerBeforeOrAtLevel: number;
  levelNeededForBadge: number;
  lifeTimeBadgeMoneySharePercent: number;
  moneyForBeingReferred: number;
}

export interface RegionResourceBonusByTier {
  "1": number;
  "2": number;
  "3": number;
}

export interface GameConfigRegion {
  battleCooldownHours: number;
  decreaseBy: number;
  decreaseResistanceCost: number;
  depleteHourlyPercent: number;
  increaseBy: number;
  increaseResistanceCost: number;
  maxDailyResistance: number;
  maxResistance: number;
  minDailyResistance: number;
  regionNotLinkedToCapitalMalusDevelopmentPercent: number;
  resistanceAllyBonusPercent: number;
  resistanceBarMultiplier: number;
  resistanceBattleCooldownHours: number;
  resistanceBattleStartCostMultiplier: number;
  resistanceCitizenBonus: number;
  resistanceCitizenBonusPercent: number;
  resistanceContributionCooldownAfterRevoltHours: number;
  resistanceContributionCost: number;
  resistanceContributionMinLevel: number;
  resistanceContributionValue: number;
  resistanceDecayPercent: number;
  resistanceForeignGovCostMultiplier: number;
  resistanceGrowthPercentMax: number;
  resistanceGrowthPercentMin: number;
  resistancePassiveGrowthPercent: number;
  resourcesBonus: RegionResourceBonusByTier;
  transferDaysCooldown: number;
}

export interface SkillLevelZero {
  totalCost: number;
  unlockAtLevel: number;
  value: number;
}

export interface SkillLevel {
  cost: number;
  totalCost: number;
  unlockAtLevel: number;
  value: number;
}

export interface SkillLevels {
  "0": SkillLevelZero;
  "1": SkillLevel;
  "10": SkillLevel;
  "2": SkillLevel;
  "3": SkillLevel;
  "4": SkillLevel;
  "5": SkillLevel;
  "6": SkillLevel;
  "7": SkillLevel;
  "8": SkillLevel;
  "9": SkillLevel;
}

export interface SkillTrack {
  levels: SkillLevels;
}

export interface BarSkillLevelZero {
  isABar: boolean;
  totalCost: number;
  unlockAtLevel: number;
  value: number;
}

export interface BarSkillLevels {
  "0": BarSkillLevelZero;
  "1": SkillLevel;
  "10": SkillLevel;
  "2": SkillLevel;
  "3": SkillLevel;
  "4": SkillLevel;
  "5": SkillLevel;
  "6": SkillLevel;
  "7": SkillLevel;
  "8": SkillLevel;
  "9": SkillLevel;
}

export interface BarSkillTrack {
  levels: BarSkillLevels;
}

export interface GameConfigSkills {
  armor: SkillTrack;
  attack: SkillTrack;
  companies: SkillTrack;
  criticalChance: SkillTrack;
  criticalDamages: SkillTrack;
  dodge: SkillTrack;
  energy: BarSkillTrack;
  entrepreneurship: BarSkillTrack;
  health: BarSkillTrack;
  hunger: BarSkillTrack;
  lootChance: SkillTrack;
  management: SkillTrack;
  precision: SkillTrack;
  production: BarSkillTrack;
}

export interface GameConfigUnrest {
  barMultiplier: number;
  battleCooldownHours: number;
  battleStartCost: number;
  bordersOpenDays: number;
  contributionCooldownAfterRevolutionHours: number;
  contributionCost: number;
  contributionMinLevel: number;
  contributionValue: number;
  nominationPeriodHours: number;
}

export interface GameConfigUpgrade {
  refundPercent: number;
  regionDowngradeCooldownHours: number;
  regionUpgradeCooldownHours: number;
}

export interface UpgradeConfigStorageStats {
  dailyProd: number;
}

export interface UpgradeConfigStorageLevel {
  constructionPointsCost: number;
  level: number;
  stats: UpgradeConfigStorageStats;
  steelCost: number;
}

export interface UpgradeConfigStorageLevels {
  "1": UpgradeConfigStorageLevel;
  "2": UpgradeConfigStorageLevel;
  "3": UpgradeConfigStorageLevel;
  "4": UpgradeConfigStorageLevel;
  "5": UpgradeConfigStorageLevel;
  "6": UpgradeConfigStorageLevel;
  "7": UpgradeConfigStorageLevel;
}

export interface UpgradeConfigAutomatedEngine {
  canDowngrade: boolean;
  levels: UpgradeConfigStorageLevels;
  pendingDurationHours: number;
}

export interface UpgradeConfigAttackBonusStats {
  attackBonus: number;
}

export interface UpgradeConfigBaseLevel {
  constructionPointsCost: number;
  level: number;
  maintenanceCostCountryDevScale: number;
  minimumMaintenanceCost: number;
  stats: UpgradeConfigAttackBonusStats;
  steelCost: number;
}

export interface UpgradeConfigBaseLevels {
  "1": UpgradeConfigBaseLevel;
  "2": UpgradeConfigBaseLevel;
  "3": UpgradeConfigBaseLevel;
  "4": UpgradeConfigBaseLevel;
  "5": UpgradeConfigBaseLevel;
}

export interface UpgradeConfigBase {
  canBeDestroyed: boolean;
  canBeDisabled: boolean;
  canDowngrade: boolean;
  levels: UpgradeConfigBaseLevels;
  pendingDurationHours: number;
}

export interface UpgradeConfigBreakRoomStats {
  dailyHires: number;
  maxWorkers: number;
}

export interface UpgradeConfigBreakRoomLevel {
  level: number;
  stats: UpgradeConfigBreakRoomStats;
  steelCost: number;
}

export interface UpgradeConfigBreakRoomLevels {
  "1": UpgradeConfigBreakRoomLevel;
  "2": UpgradeConfigBreakRoomLevel;
  "3": UpgradeConfigBreakRoomLevel;
  "4": UpgradeConfigBreakRoomLevel;
  "5": UpgradeConfigBreakRoomLevel;
}

export interface UpgradeConfigBreakRoom {
  canDowngrade: boolean;
  levels: UpgradeConfigBreakRoomLevels;
}

export interface UpgradeConfigDefenseBonusStats {
  defenseBonus: number;
}

export interface UpgradeConfigBunkerLevel {
  constructionPointsCost: number;
  level: number;
  maintenanceCostCountryDevScale: number;
  minimumMaintenanceCost: number;
  stats: UpgradeConfigDefenseBonusStats;
  steelCost: number;
}

export interface UpgradeConfigBunkerLevels {
  "1": UpgradeConfigBunkerLevel;
  "2": UpgradeConfigBunkerLevel;
  "3": UpgradeConfigBunkerLevel;
  "4": UpgradeConfigBunkerLevel;
  "5": UpgradeConfigBunkerLevel;
}

export interface UpgradeConfigBunker {
  canBeDestroyed: boolean;
  canBeDisabled: boolean;
  canDowngrade: boolean;
  levels: UpgradeConfigBunkerLevels;
  pendingDurationHours: number;
}

export interface UpgradeConfigDormitoriesStats {
  members: number;
}

export interface UpgradeConfigDormitoriesLevel {
  level: number;
  stats: UpgradeConfigDormitoriesStats;
  steelCost: number;
}

export interface UpgradeConfigDormitoriesLevels {
  "1": UpgradeConfigDormitoriesLevel;
  "2": UpgradeConfigDormitoriesLevel;
  "3": UpgradeConfigDormitoriesLevel;
  "4": UpgradeConfigDormitoriesLevel;
  "5": UpgradeConfigDormitoriesLevel;
}

export interface UpgradeConfigDormitories {
  canDowngrade: boolean;
  levels: UpgradeConfigDormitoriesLevels;
}

export interface UpgradeConfigHeadquartersLevel {
  level: number;
  maintenanceCost: number;
  stats: UpgradeConfigAttackBonusStats;
  steelCost: number;
}

export interface UpgradeConfigHeadquartersLevels {
  "1": UpgradeConfigHeadquartersLevel;
  "2": UpgradeConfigHeadquartersLevel;
  "3": UpgradeConfigHeadquartersLevel;
  "4": UpgradeConfigHeadquartersLevel;
}

export interface UpgradeConfigHeadquarters {
  canBeDisabled: boolean;
  canDowngrade: boolean;
  levels: UpgradeConfigHeadquartersLevels;
  pendingDurationHours: number;
}

export interface UpgradeConfigPacificationCenterStats {
  resistanceGrowthReduction: number;
}

export interface UpgradeConfigPacificationCenterLevel {
  constructionPointsCost: number;
  level: number;
  maintenanceCostRegionDevScale: number;
  minimumMaintenanceCost: number;
  stats: UpgradeConfigPacificationCenterStats;
  steelCost: number;
}

export interface UpgradeConfigPacificationCenterLevels {
  "1": UpgradeConfigPacificationCenterLevel;
  "2": UpgradeConfigPacificationCenterLevel;
  "3": UpgradeConfigPacificationCenterLevel;
  "4": UpgradeConfigPacificationCenterLevel;
  "5": UpgradeConfigPacificationCenterLevel;
}

export interface UpgradeConfigPacificationCenter {
  canBeDestroyed: boolean;
  canBeDisabled: boolean;
  canDowngrade: boolean;
  levels: UpgradeConfigPacificationCenterLevels;
  pendingDurationHours: number;
}

export interface UpgradeConfigStorageCapacityStats {
  maxProduction: number;
}

export interface UpgradeConfigStorageCapacityLevel {
  constructionPointsCost: number;
  level: number;
  stats: UpgradeConfigStorageCapacityStats;
  steelCost: number;
}

export interface UpgradeConfigStorageCapacityLevels {
  "1": UpgradeConfigStorageCapacityLevel;
  "2": UpgradeConfigStorageCapacityLevel;
  "3": UpgradeConfigStorageCapacityLevel;
  "4": UpgradeConfigStorageCapacityLevel;
  "5": UpgradeConfigStorageCapacityLevel;
  "6": UpgradeConfigStorageCapacityLevel;
  "7": UpgradeConfigStorageCapacityLevel;
}

export interface UpgradeConfigStorage {
  canDowngrade: boolean;
  levels: UpgradeConfigStorageCapacityLevels;
  pendingDurationHours: number;
}

export interface GameConfigUpgradesConfig {
  automatedEngine: UpgradeConfigAutomatedEngine;
  base: UpgradeConfigBase;
  breakRoom: UpgradeConfigBreakRoom;
  bunker: UpgradeConfigBunker;
  dormitories: UpgradeConfigDormitories;
  headquarters: UpgradeConfigHeadquarters;
  pacificationCenter: UpgradeConfigPacificationCenter;
  storage: UpgradeConfigStorage;
}

export interface UserDailyReward {
  case1: number;
  money: number;
  xp: number;
}

export interface UserEquipmentSets {
  nonPremiumMax: number;
  premiumMax: number;
}

export interface GameConfigUser {
  activeCitizenMinLevel: number;
  canTakeControlAtLevel: number;
  chatMinLevel: number;
  citizenshipDaysCooldown: number;
  constructionEnergyCost: number;
  dailyReward: UserDailyReward;
  dailyXp: number;
  donationMinLevel: number;
  energyCostPerAction: number;
  equipmentSets: UserEquipmentSets;
  fieldsToPopulate: string;
  isInactiveAfterDays: number;
  marketMinLevel: number;
  maxConstructionPoints: number;
  maxEnergy: number;
  maxHunger: number;
  regenDividedBy: number;
  resetSkillDaysCooldown: number;
  resetSkillsCostPerPoint: number;
  takeControlCooldownInDays: number;
  xpPerAction: number;
}

export interface GameConfigWorker {
  fidelityProductionBonusPercent: number;
  maxFidelity: number;
}

export interface MuActiveUpgradeLevels {
  dormitories?: number;
  headquarters?: number;
}

export interface MuRankings {
  muBounty: RankingValueTier;
  muDamages: RankingValueTier;
  muTerrain: RankingValueTier;
  muWealth: RankingValueTier;
  muWeeklyDamages: RankingValueTier;
}

export interface MuRoles {
  commanders: Array<string>;
  managers: Array<string>;
}

export interface MuRankingsOptional {
  muBounty?: RankingValueTier;
  muDamages?: RankingValueTier;
  muTerrain?: RankingValueTier;
  muWealth: RankingValueTier;
  muWeeklyDamages?: RankingValueTier;
}

export interface MuListItem {
  __v: number;
  _id: string;
  activeUpgradeLevels: MuActiveUpgradeLevels;
  avatarUrl?: string;
  createdAt: string;
  members: Array<string>;
  name: string;
  rankings: MuRankingsOptional;
  region: string;
  roles: MuRoles;
  updatedAt: string;
  user: string;
}

export interface RankingItem {
  _id: string;
  country: string;
  rank: number;
  tier: string;
  value: number;
}

export interface RankingTierValues {
  bronze: number;
  diamond: number;
  gold: number;
  master: number;
  platinum: number;
  silver: number;
}

export interface RegionActiveUpgradeLevels {
  base?: number;
  bunker?: number;
  pacificationCenter?: number;
}

export interface RegionDates {
  lastOwnershipChangeAt?: string;
}

export interface RegionDeposit {
  bonusPercent: number;
  endsAt: string;
  startsAt: string;
  type: string;
}

export interface RegionStats {
  investedMoney: number;
}

export interface RegionUpgradeConstructionHistory {
  constructionEndedAt: string;
  constructionPoints: number;
  constructionStartedAt: string;
  investedMoney: number;
  isUnderConstruction?: unknown;
  lastConstructions: unknown[];
  level: number;
  status: string;
  statusChangedAt?: string;
}

export interface RegionUpgradeBunker {
  construction: number;
  constructionAt: string;
  user: string;
}

export interface RegionUpgrades {
  constructionEndedAt?: string;
  constructionPoints: number;
  constructionStartedAt: string;
  investedMoney: number;
  isUnderConstruction?: boolean;
  lastConstructions: Array<RegionUpgradeBunker>;
  level: number;
  status?: string;
  statusChangedAt?: string;
}

export interface RegionUpgradesV2 {
  base?: RegionUpgradeConstructionHistory;
  bunker?: RegionUpgrades;
}

export interface RegionByIdItem {
  activeConstructionCount?: number;
  upgrades: RegionUpgradesV2;
}

export interface BattleSideSummaryRequiredRegion {
  __v: number;
  _id: string;
  activeBattle?: string;
  activeUpgradeLevels?: RegionActiveUpgradeLevels;
  baseDevelopment: number;
  biome: string;
  climate: string;
  code: string;
  country: string;
  countryCode: string;
  dates: RegionDates;
  deposit?: RegionDeposit;
  development: number;
  hasCoast?: boolean;
  initialCountry: string;
  isCapital: boolean;
  isLinkedToCapital: boolean;
  lastBattleEndedAt?: string;
  lastResistanceContributionAt?: string;
  lastRevoltEndedAt?: string;
  mainCity: string;
  name: string;
  neighbors: Array<string>;
  position: Array<number>;
  resistance: number;
  resistanceMax: number;
  stats: RegionStats;
  strategicResource?: string;
  upgradesV2: RegionByIdItem;
}

export interface RegionActiveBattle {
  __v: number;
  _id: string;
  attacker: BattleSideSummary;
  createdAt: string;
  currentRound: string;
  defender: BattleDefenderSummary;
  isActive: boolean;
  isBigBattle?: boolean;
  rounds: Array<string>;
  roundsHistory: Array<string>;
  roundsToWin: number;
  stats: BattleStats;
  type: string;
  updatedAt: string;
  war: string;
}

export interface RegionsObjectItem {
  __v: number;
  _id: string;
  activeBattle?: RegionActiveBattle;
  activeUpgradeLevels?: RegionActiveUpgradeLevels;
  baseDevelopment: number;
  biome: string;
  climate: string;
  code: string;
  country: string;
  countryCode: string;
  dates: RegionDates;
  deposit?: RegionDeposit;
  development: number;
  hasCoast?: boolean;
  initialCountry: string;
  isCapital: boolean;
  isLinkedToCapital: boolean;
  lastBattleEndedAt?: string;
  lastResistanceContributionAt?: string;
  lastRevoltEndedAt?: string;
  mainCity: string;
  name: string;
  neighbors: Array<string>;
  position: Array<number>;
  resistance: number;
  resistanceMax: number;
  stats: RegionStats;
  strategicResource?: string;
  upgradesV2: RegionByIdItem;
}

export interface RoundLastHitWithWeapon {
  _id: string;
  ammo?: string;
  damages: number;
  hitAt: string;
  isCriticalHit: boolean;
  missed: boolean;
  mu?: string;
  user: string;
  weapon?: RoundWeapon;
}

export interface RoundSideCombatStatsWithWeapon {
  country: string;
  damages: number;
  hitCount: number;
  lastHits: Array<RoundLastHitWithWeapon>;
  points: number;
}

export interface TradingOrderWithMu {
  __v: number;
  _id: string;
  itemCode: string;
  mu?: string;
  offerAt: string;
  price: number;
  quantity: number;
  type: string;
  user: string;
}

export interface TradingOrder {
  __v: number;
  _id: string;
  itemCode: string;
  offerAt: string;
  price: number;
  quantity: number;
  type: string;
  user: string;
}

export interface EquipmentSkillsMixed {
  armor?: number;
  attack?: number;
  criticalChance?: number;
  criticalDamages?: number;
  dodge?: number;
  precision?: number;
}

export interface TransactionItem {
  _id: string;
  code: string;
  lastAcquisitionAt: string;
  maxState: number;
  quantity: number;
  skills: EquipmentSkillsMixed;
  state: number;
  type?: string;
}

export interface TransactionListItem {
  __v: number;
  _id: string;
  buyerId: string;
  createdAt: string;
  item?: TransactionItem;
  itemCode?: string;
  money?: number;
  offerCreatedAt?: string;
  quantity?: number;
  sellerCountryId?: string;
  sellerId?: string;
  sellerMuId?: string;
  transactionType: string;
  updatedAt: string;
}

export interface UserDates {
  lastCitizenshipChangeAt: string;
  lastCompanyJoinedAt: string;
  lastConnectionAt: string;
  lastCountryMessageCheckAt: string;
  lastDailyRewardClaimedAt: string;
  lastEventsCheckAt: string;
  lastGlobalMessageCheckAt: string;
  lastHelpAskedAt: string;
  lastHiresAt: Array<string>;
  lastNotificationsCheckAt: string;
  lastSkillsResetAt: string;
  lastTakingControlAt: string;
  lastWorkAt: string;
  lastWorkOfferApplications: Array<string>;
}

export interface UserInfos {
  colorScheme: string;
  description: string;
  font: string;
  isPremium: boolean;
  premiumGiftsCount: number;
  premiumMonthsCount: number;
  vicePresidentOf: string;
}

export interface UserLeveling {
  availableSkillPoints: number;
  dailyXpLeft: number;
  freeReset: number;
  level: number;
  spentSkillPoints: number;
  totalSkillPoints: number;
  totalXp: number;
}

export interface UserRankings {
  userBounty: RankingValueTier;
  userCasesOpened: RankingValueTier;
  userDamages: RankingValueTier;
  userGemsPurchased: RankingValueTier;
  userLevel: RankingValueTier;
  userPremiumGifts: RankingValueTier;
  userPremiumMonths: RankingValueTier;
  userReferrals: RankingValueTier;
  userSubscribers: RankingValueTier;
  userTerrain: RankingValueTier;
  userWealth: RankingValueTier;
  weeklyUserDamages: RankingValueTier;
}

export interface UserSkillComputedStandard {
  equipment: number;
  level: number;
  limited?: unknown;
  total: number;
  totalAfterSoftCap?: unknown;
  value?: unknown;
  weapon?: unknown;
}

export interface UserSkillComputedAttack {
  ammoPercent: number;
  buffsPercent: number;
  debuffsPercent: number;
  equipment?: unknown;
  level: number;
  limited?: unknown;
  militaryRankPercent: number;
  total: number;
  totalAfterSoftCap?: unknown;
  value: number;
  weapon: number;
}

export interface UserSkillComputedCompany {
  equipment?: unknown;
  level: number;
  limited?: unknown;
  total: number;
  totalAfterSoftCap?: unknown;
  value: number;
  weapon?: unknown;
}

export interface UserSkillComputedCriticalChance {
  equipment?: unknown;
  level: number;
  limited?: unknown;
  total: number;
  totalAfterSoftCap?: unknown;
  value: number;
  weapon: number;
}

export interface UserSkillComputedPrecision {
  equipment: number;
  level: number;
  limited?: unknown;
  total: number;
  totalAfterSoftCap?: unknown;
  value: number;
  weapon?: unknown;
}

export interface UserSkillComputedBar {
  currentBarValue: number;
  equipment?: unknown;
  hourlyBarRegen: number;
  level: number;
  limited?: unknown;
  total: number;
  totalAfterSoftCap?: unknown;
  value: number;
  weapon?: unknown;
}

export interface UserSkills {
  armor: UserSkillComputedStandard;
  attack: UserSkillComputedAttack;
  companies: UserSkillComputedCompany;
  criticalChance: UserSkillComputedCriticalChance;
  criticalDamages: UserSkillComputedPrecision;
  dodge: UserSkillComputedStandard;
  energy: UserSkillComputedBar;
  entrepreneurship: UserSkillComputedBar;
  health: UserSkillComputedBar;
  hunger: UserSkillComputedBar;
  lootChance: UserSkillComputedCompany;
  management: UserSkillComputedCompany;
  precision: UserSkillComputedPrecision;
  production: UserSkillComputedBar;
}

export interface UserStats {
  damagesCount: number;
}

export interface UsersByCountryItem {
  _id: string;
  createdAt: string;
}

export interface WorkerCompany {
  _id: string;
  itemCode: string;
  name: string;
}

export interface WorkersPerCompanyItem {
  company: WorkerCompany;
  workers: unknown[];
}

export interface WorkOfferListItem {
  __v: number;
  _id: string;
  citizenship?: string;
  company: string;
  createdAt: string;
  initialQuantity: number;
  minEnergy?: number;
  minProduction?: number;
  quantity: number;
  region: string;
  text?: string;
  updatedAt: string;
  user: string;
  wage: number;
}

export type ArticleGetArticleByIdResponse = {
  __v: number;
  _id: string;
  author: string;
  category: string;
  content: string;
  createdAt: string;
  isDeleted: boolean;
  isPublished: boolean;
  language: string;
  publishedAt: string;
  stats: ArticleStats;
  title: string;
  updatedAt: string;
};

export type ArticleGetArticleLiteByIdResponse = {
  _id: string;
  stats: ArticleStats;
  title: string;
};

export type ArticleGetArticlesPaginatedResponse = {
  items: Array<ArticleListItem>;
  nextCursor?: string;
};

export type BattleGetBattlesResponse = {
  items: Array<BattleListItem>;
  nextCursor?: string;
};

export type BattleGetByIdResponse = {
  __v: number;
  _id: string;
  attacker: BattleDetailedSide;
  badgesProcessed: boolean;
  createdAt: string;
  currentRound: string;
  defender: BattleDetailedSide;
  endedAt: string;
  isActive: boolean;
  isResistance: boolean;
  rounds: Array<string>;
  roundsHistory: Array<string>;
  roundsToWin: number;
  stats: BattleStats;
  type: string;
  updatedAt: string;
  war: string;
  wonBy: string;
};

export type BattleGetLiveBattleDataResponse = {
  battle: LiveBattleSummary;
  round: LiveRoundSummary;
};

export type BattleRankingGetRankingResponse = {
  rankings: Array<{
    country: string;
    value: number;
    rank: number;
    _id: string;
  }>;
};

export type CompanyGetByIdResponse = {
  __v: number;
  _id: string;
  activeUpgradeLevels: CompanyActiveUpgradeLevels;
  concreteInvested: number;
  createdAt: string;
  dates: CompanyDates;
  estimatedValue: number;
  isFull: boolean;
  itemCode: string;
  movedUpAt: string;
  name: string;
  production: number;
  region: string;
  updatedAt: string;
  user: string;
  workerCount: number;
  workers: unknown[];
};

export type CompanyGetCompaniesResponse = {
  items: Array<string>;
  nextCursor?: string;
};

export type CountryGetAllCountriesResponse = Array<CountryListItem>;

export type CountryGetCountryByIdResponse = {
  __v: number;
  _id: string;
  allies: Array<string>;
  code: string;
  createdAt: string;
  development: number;
  discordUrl: string;
  mapAccent: string;
  money: number;
  name: string;
  orgs: unknown[];
  rankings: CountryRankings;
  rulingParty: string;
  scheme: string;
  specializedItem: string;
  strategicResources: CountryStrategicResourceConfigGoldOnly;
  taxes: CountryTaxes;
  unrest: CountryUnrest;
  updatedAt: string;
  warsWith: Array<string>;
};

export type EventGetEventsPaginatedResponse = {
  items: Array<EventListItem>;
  nextCursor?: string;
};

export type GameConfigGetDatesResponse = {
  dailyMissionRegenAt: string;
  nextCongressElectionsAt: string;
  nextDayAt: string;
  nextMonthAt: string;
  nextPresidentialElectionsAt: string;
  nextRegenAt: string;
  previousDayAt: string;
  weeklyMissionRegenAt: string;
};

export type GameConfigGetGameConfigResponse = {
  badge: GameConfigBadges;
  battle: GameConfigBattle;
  citizenshipApplication: GameConfigCitizenshipApplication;
  company: GameConfigCompany;
  country: GameConfigCountry;
  election: GameConfigElection;
  government: GameConfigGovernment;
  items: GameConfigItems;
  law: GameConfigLaw;
  mergingCost: MergingCostByRarity;
  mission: GameConfigMission;
  mu: GameConfigMu;
  newspaper: GameConfigNewspaper;
  org: GameConfigOrg;
  party: GameConfigParty;
  referral: GameConfigReferral;
  region: GameConfigRegion;
  skills: GameConfigSkills;
  unrest: GameConfigUnrest;
  upgrade: GameConfigUpgrade;
  upgradesConfig: GameConfigUpgradesConfig;
  user: GameConfigUser;
  worker: GameConfigWorker;
};

export type GovernmentGetByCountryIdResponse = {
  __v: number;
  _id: string;
  congressMembers: Array<string>;
  country: string;
  minOfDefense: string;
  minOfEconomy: string;
  minOfForeignAffairs: string;
  president: string;
  vicePresident: string;
};

export type ItemTradingGetPricesResponse = {
  ammo: number;
  bread: number;
  case1: number;
  case2: number;
  coca: number;
  cocain: number;
  concrete: number;
  cookedFish: number;
  fish: number;
  grain: number;
  heavyAmmo: number;
  iron: number;
  lead: number;
  lightAmmo: number;
  limestone: number;
  livestock: number;
  oil: number;
  petroleum: number;
  scraps: number;
  steak: number;
  steel: number;
};

export type MuGetByIdResponse = {
  __v: number;
  _id: string;
  activeUpgradeLevels: MuActiveUpgradeLevels;
  avatarUrl: string;
  createdAt: string;
  members: Array<string>;
  name: string;
  rankings: MuRankings;
  region: string;
  roles: MuRoles;
  updatedAt: string;
  user: string;
};

export type MuGetManyPaginatedResponse = {
  items: Array<MuListItem>;
  nextCursor?: string;
};

export type RankingGetRankingResponse = {
  __v: number;
  _id: string;
  isGlobal: boolean;
  items: Array<RankingItem>;
  tierValues: RankingTierValues;
  type: string;
};

export type RegionGetByIdResponse = Array<BattleSideSummaryRequiredRegion>;

export type RegionGetRegionsObjectResponse = Record<string, RegionsObjectItem>;

export type RoundGetByIdResponse = {
  __v: number;
  _id: string;
  attacker: RoundSideCombatStatsWithWeapon;
  badgesProcessed: boolean;
  battle: string;
  createdAt: string;
  defender: RoundSideCombatStatsWithWeapon;
  endedAt: string;
  isActive: boolean;
  live: RoundLiveState;
  number: number;
  updatedAt: string;
  wonBy: string;
};

export type RoundGetLastHitsResponse = {
  attacker: Array<RoundLastHitWithWeapon>;
  defender: Array<RoundLastHitWithWeapon>;
};

export type SearchSearchAnythingResponse = {
  countryIds: unknown[];
  hasData: boolean;
  muIds: Array<string>;
  partyIds: unknown[];
  regionIds: unknown[];
  userIds: Array<string>;
};

export type TradingOrderGetTopOrdersResponse = {
  buyOrders: Array<TradingOrderWithMu>;
  sellOrders: Array<TradingOrder>;
};

export type TransactionGetPaginatedTransactionsResponse = {
  items: Array<TransactionListItem>;
  nextCursor?: string;
};

export type UpgradeGetUpgradeByTypeAndEntityResponse = {
  __v: number;
  _id: string;
  createdAt: string;
  dependantUsersCount: number;
  investedConcrete: number;
  investedMoney: number;
  investedSteel: number;
  level: number;
  region: string;
  status: string;
  statusChangedAt: string;
  updatedAt: string;
  upgradeType: string;
  willBeActiveAt: string;
};

export type UserGetUserLiteResponse = {
  _id: string;
  avatarUrl: string;
  country: string;
  createdAt: string;
  dates: UserDates;
  infos: UserInfos;
  isActive: boolean;
  leveling: UserLeveling;
  militaryRank: number;
  mu: string;
  rankings: UserRankings;
  skills: UserSkills;
  stats: UserStats;
  username: string;
};

export type UserGetUsersByCountryResponse = {
  items: Array<UsersByCountryItem>;
  nextCursor?: string;
};

export type WorkerGetTotalWorkersCountResponse = number;

export type WorkerGetWorkersResponse = {
  type: string;
  workersPerCompany: Array<WorkersPerCompanyItem>;
};

export type WorkOfferGetByIdResponse = {
  __v: number;
  _id: string;
  citizenship: string;
  company: string;
  createdAt: string;
  initialQuantity: number;
  minEnergy: number;
  minProduction: number;
  quantity: number;
  region: string;
  updatedAt: string;
  user: string;
  wage: number;
};

export type WorkOfferGetWorkOfferByCompanyIdResponse = {
  __v: number;
  _id: string;
  company: string;
  createdAt: string;
  initialQuantity: number;
  minEnergy: number;
  minProduction: number;
  quantity: number;
  region: string;
  text: string;
  updatedAt: string;
  user: string;
  wage: number;
};

export type WorkOfferGetWorkOffersPaginatedResponse = {
  items: Array<WorkOfferListItem>;
  nextCursor?: string;
};

export interface Responses {
  "article.getArticleById": ArticleGetArticleByIdResponse;
  "article.getArticleLiteById": ArticleGetArticleLiteByIdResponse;
  "article.getArticlesPaginated": ArticleGetArticlesPaginatedResponse;
  "battle.getBattles": BattleGetBattlesResponse;
  "battle.getById": BattleGetByIdResponse;
  "battle.getLiveBattleData": BattleGetLiveBattleDataResponse;
  "battleRanking.getRanking": BattleRankingGetRankingResponse;
  "company.getById": CompanyGetByIdResponse;
  "company.getCompanies": CompanyGetCompaniesResponse;
  "country.getAllCountries": CountryGetAllCountriesResponse;
  "country.getCountryById": CountryGetCountryByIdResponse;
  "event.getEventsPaginated": EventGetEventsPaginatedResponse;
  "gameConfig.getDates": GameConfigGetDatesResponse;
  "gameConfig.getGameConfig": GameConfigGetGameConfigResponse;
  "government.getByCountryId": GovernmentGetByCountryIdResponse;
  "itemTrading.getPrices": ItemTradingGetPricesResponse;
  "mu.getById": MuGetByIdResponse;
  "mu.getManyPaginated": MuGetManyPaginatedResponse;
  "ranking.getRanking": RankingGetRankingResponse;
  "region.getById": RegionGetByIdResponse;
  "region.getRegionsObject": RegionGetRegionsObjectResponse;
  "round.getById": RoundGetByIdResponse;
  "round.getLastHits": RoundGetLastHitsResponse;
  "search.searchAnything": SearchSearchAnythingResponse;
  "tradingOrder.getTopOrders": TradingOrderGetTopOrdersResponse;
  "transaction.getPaginatedTransactions": TransactionGetPaginatedTransactionsResponse;
  "upgrade.getUpgradeByTypeAndEntity": UpgradeGetUpgradeByTypeAndEntityResponse;
  "user.getUserLite": UserGetUserLiteResponse;
  "user.getUsersByCountry": UserGetUsersByCountryResponse;
  "worker.getTotalWorkersCount": WorkerGetTotalWorkersCountResponse;
  "worker.getWorkers": WorkerGetWorkersResponse;
  "workOffer.getById": WorkOfferGetByIdResponse;
  "workOffer.getWorkOfferByCompanyId": WorkOfferGetWorkOfferByCompanyIdResponse;
  "workOffer.getWorkOffersPaginated": WorkOfferGetWorkOffersPaginatedResponse;
}
