/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/company.getById": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get company by ID
         * @description Retrieves detailed information about a specific company
         */
        post: operations["company.getById"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/company.getCompanies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get companies with pagination
         * @description Retrieves a paginated list of companies with optional filtering
         */
        post: operations["company.getCompanies"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/country.getCountryById": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get country by ID
         * @description Retrieves detailed information about a specific country
         */
        post: operations["country.getCountryById"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/country.getAllCountries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get all countries
         * @description Retrieves a list of all available countries
         */
        post: operations["country.getAllCountries"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event.getEventsPaginated": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get paginated events
         * @description Retrieves a paginated list of events with optional country and event type filters
         */
        post: operations["event.getEventsPaginated"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/government.getByCountryId": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get government by country ID
         * @description Retrieves government information for a specific country
         */
        post: operations["government.getByCountryId"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/region.getById": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get region by ID
         * @description Retrieves detailed information about a specific region
         */
        post: operations["region.getById"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/region.getRegionsObject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get all regions
         * @description Retrieves a complete object containing all available regions
         */
        post: operations["region.getRegionsObject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/battle.getById": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get battle by ID
         * @description Retrieves detailed information about a specific battle
         */
        post: operations["battle.getById"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/battle.getLiveBattleData": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get live battle data
         * @description Retrieves real-time battle data including current round information
         */
        post: operations["battle.getLiveBattleData"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/battle.getBattles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get battles
         * @description Retrieves a list of battles
         */
        post: operations["battle.getBattles"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/round.getById": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get round by ID
         * @description Retrieves detailed information about a specific battle round
         */
        post: operations["round.getById"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/round.getLastHits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get last hits in round
         * @description Retrieves the most recent hits/damages in a specific battle round
         */
        post: operations["round.getLastHits"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/battleRanking.getRanking": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get battle rankings
         * @description Retrieves damage, ground, or money rankings for users or countries in battles, rounds, or wars
         */
        post: operations["battleRanking.getRanking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/itemTrading.getPrices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get item prices
         * @description Retrieves current market prices for all tradeable items
         */
        post: operations["itemTrading.getPrices"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tradingOrder.getTopOrders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get best orders for an item
         * @description Retrieves the best orders for an item
         */
        post: operations["tradingOrder.getTopOrders"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/itemOffer.getById": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get item offer by ID
         * @description Retrieves detailed information about a specific item offer
         */
        post: operations["itemOffer.getById"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workOffer.getById": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get work offer by ID
         * @description Retrieves detailed information about a specific work offer
         */
        post: operations["workOffer.getById"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workOffer.getWorkOfferByCompanyId": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get work offer by company ID
         * @description Retrieves work offer for a specific company
         */
        post: operations["workOffer.getWorkOfferByCompanyId"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workOffer.getWorkOffersPaginated": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get paginated work offers
         * @description Retrieves a paginated list of work offers with optional user and region filtering
         */
        post: operations["workOffer.getWorkOffersPaginated"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ranking.getRanking": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get ranking data
         * @description Retrieves ranking data for the specified ranking type and optional year-week filter
         */
        post: operations["ranking.getRanking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search.searchAnything": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Global search
         * @description Performs a global search across users, countries, regions, military units, parties, and other entities
         */
        post: operations["search.searchAnything"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gameConfig.getDates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get game dates
         * @description Retrieves game-related dates and timings
         */
        post: operations["gameConfig.getDates"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gameConfig.getGameConfig": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get game configuration
         * @description Retrieves static game configuration
         */
        post: operations["gameConfig.getGameConfig"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user.getUserLite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get user profile (lite)
         * @description Retrieves basic public information about a user including username, skills, and rankings
         */
        post: operations["user.getUserLite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user.getUsersByCountry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get users by country
         * @description Retrieves a list of users by country
         */
        post: operations["user.getUsersByCountry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user.getUserById": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get user by ID
         * @description Retrieves public information about a user by their ID
         */
        post: operations["user.getUserById"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/article.getArticleById": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get article by ID
         * @description Retrieves detailed information about a specific article
         */
        post: operations["article.getArticleById"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/article.getArticleLiteById": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get article lite by ID
         * @description Retrieves only the title and basic stats of an article without counting as a view
         */
        post: operations["article.getArticleLiteById"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/article.getArticlesPaginated": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get paginated articles
         * @description Retrieves a paginated list of articles
         */
        post: operations["article.getArticlesPaginated"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mu.getById": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get military unit by ID
         * @description Retrieves detailed information about a specific military unit
         */
        post: operations["mu.getById"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mu.getManyPaginated": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get military units (paginated)
         * @description Retrieves a paginated list of military units with optional filters
         */
        post: operations["mu.getManyPaginated"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transaction.getPaginatedTransactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get paginated transactions
         * @description Retrieves a paginated list of transactions
         */
        post: operations["transaction.getPaginatedTransactions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/upgrade.getUpgradeByTypeAndEntity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get upgrade by type and entity
         * @description Retrieves upgrade information for a specific upgrade type and entity (region, company, or military unit)
         */
        post: operations["upgrade.getUpgradeByTypeAndEntity"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/worker.getWorkers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get workers
         * @description Get workers for a company or user
         */
        post: operations["worker.getWorkers"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/worker.getTotalWorkersCount": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get total workers count
         * @description Get total workers count for a user
         */
        post: operations["worker.getTotalWorkersCount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/battleOrder.getByBattle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get battle orders
         * @description Retrieves active battle orders for a specific battle and side
         */
        post: operations["battleOrder.getByBattle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/battleLootSummary.getByBattleAndUser": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get battle loot summary by battle and user
         * @description Retrieves the loot summary for a specific user in a specific battle, including case counts, hits, total damage and pool loot.
         */
        post: operations["battleLootSummary.getByBattleAndUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inventory.fetchCurrentEquipment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get equipped items
         * @description Retrieves the currently equipped items for a user
         */
        post: operations["inventory.fetchCurrentEquipment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mercenaryContractAuction.getPaginatedAuctions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get active mercenary contract auctions with optional filters
         * @description Retrieves a list of active mercenary contract auctions, with optional filtering by country, battle, and status
         */
        post: operations["mercenaryContractAuction.getPaginatedAuctions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "company.getById": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @description The unique identifier of the company */
                    companyId: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "company.getCompanies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @description Filter companies by user ID */
                    userId?: string;
                    /**
                     * @description Number of companies per page (1-100)
                     * @default 10
                     */
                    perPage?: number;
                    /** @description Pagination cursor for next page */
                    cursor?: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "country.getCountryById": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @description The unique identifier of the country */
                    countryId: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "country.getAllCountries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "event.getEventsPaginated": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /**
                     * @description The limit of events to get
                     * @default 10
                     */
                    limit?: number;
                    /** @description The cursor to get the next events */
                    cursor?: string;
                    /** @description Filter events by country ID */
                    countryId?: string;
                    /** @description Filter events by event types */
                    eventTypes?: ("warDeclared" | "peace_agreement" | "battleOpened" | "battleEnded" | "newPresident" | "regionTransfer" | "peaceMade" | "countryMoneyTransfer" | "depositDiscovered" | "depositDepleted" | "systemRevolt" | "bankruptcy" | "allianceFormed" | "allianceBroken" | "regionLiberated" | "strategicResourcesReshuffled" | "resistanceIncreased" | "resistanceDecreased" | "revolutionStarted" | "revolutionEnded" | "financedRevolt")[];
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "government.getByCountryId": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @description The unique identifier of the country */
                    countryId: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "region.getById": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @description The unique identifier of the region */
                    regionId: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "region.getRegionsObject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "battle.getById": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @description The unique identifier of the battle */
                    battleId: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "battle.getLiveBattleData": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @description The unique identifier of the battle */
                    battleId: string;
                    /** @description Optional specific round number to retrieve */
                    roundNumber?: number;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "battle.getBattles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @description Whether to get active battles */
                    isActive?: boolean;
                    /**
                     * @description The limit of battles to get
                     * @default 10
                     */
                    limit?: number;
                    /** @description The cursor to get the next battles */
                    cursor?: string;
                    /**
                     * @description The direction to get the battles
                     * @enum {string}
                     */
                    direction?: "forward" | "backward";
                    /**
                     * @description Filter type for battles
                     * @enum {string}
                     */
                    filter?: "all" | "yourCountry" | "yourEnemies";
                    /** @description Filter battles by defender region ID */
                    defenderRegionId?: string;
                    /** @description Filter battles by war ID */
                    warId?: string;
                    /** @description Filter battles by country ID */
                    countryId?: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "round.getById": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @description The unique identifier of the round */
                    roundId: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "round.getLastHits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @description The unique identifier of the round */
                    roundId: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "battleRanking.getRanking": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @description Optional battle ID to filter rankings */
                    battleId?: string;
                    /** @description Optional round ID to filter rankings */
                    roundId?: string;
                    /** @description Optional war ID to filter rankings */
                    warId?: string;
                    /**
                     * @description Type of ranking data to retrieve (damage, ground points, or money)
                     * @enum {string}
                     */
                    dataType: "damage" | "points" | "money";
                    /**
                     * @description Whether to rank by user or country
                     * @enum {string}
                     */
                    type: "user" | "country" | "mu";
                    /**
                     * @description Which side of the battle to rank
                     * @enum {string}
                     */
                    side: "attacker" | "defender" | "merged";
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "itemTrading.getPrices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "tradingOrder.getTopOrders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @description The item code to get orders for */
                    itemCode: string;
                    /**
                     * @description The limit of orders to get
                     * @default 10
                     */
                    limit?: number;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "itemOffer.getById": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    itemOfferId: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "workOffer.getById": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    workOfferId: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "workOffer.getWorkOfferByCompanyId": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    companyId: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "workOffer.getWorkOffersPaginated": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    userId?: string;
                    regionId?: string;
                    cursor?: string;
                    /** @default 10 */
                    limit?: number;
                    energy?: number;
                    production?: number;
                    citizenship?: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "ranking.getRanking": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /**
                     * @description The type of ranking to retrieve
                     * @enum {string}
                     */
                    rankingType: "weeklyCountryDamages" | "weeklyCountryDamagesPerCitizen" | "countryRegionDiff" | "countryDevelopment" | "countryActivePopulation" | "countryDamages" | "countryWealth" | "countryProductionBonus" | "countryBounty" | "weeklyUserDamages" | "userDamages" | "userWealth" | "userLevel" | "userReferrals" | "userSubscribers" | "userTerrain" | "userPremiumMonths" | "userPremiumGifts" | "userCasesOpened" | "userGemsPurchased" | "userBounty" | "muWeeklyDamages" | "muDamages" | "muTerrain" | "muWealth" | "muBounty" | "muReputation";
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "search.searchAnything": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @description The search query string */
                    searchText: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "gameConfig.getDates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "gameConfig.getGameConfig": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "user.getUserLite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @description The unique identifier of the user */
                    userId: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "user.getUsersByCountry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    countryId: string;
                    /** @default 10 */
                    limit?: number;
                    cursor?: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "user.getUserById": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    userId: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "article.getArticleById": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @description The ID of the article to get */
                    articleId: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "article.getArticleLiteById": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @description The ID of the article to get */
                    articleId: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "article.getArticlesPaginated": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /**
                     * @description The type of articles to get
                     * @enum {string}
                     */
                    type: "daily" | "weekly" | "top" | "my" | "subscriptions" | "last";
                    /**
                     * @description The limit of articles to get
                     * @default 10
                     */
                    limit?: number;
                    cursor?: string;
                    /** @description The user ID to get articles for */
                    userId?: string;
                    /** @description The categories to get articles for */
                    categories?: string[];
                    /** @description The languages to get articles for */
                    languages?: string[];
                    /** @description Only show articles with a positive score */
                    positiveScoreOnly?: boolean;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "mu.getById": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    muId: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "mu.getManyPaginated": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @default 20 */
                    limit?: number;
                    cursor?: string;
                    memberId?: string;
                    userId?: string;
                    search?: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "transaction.getPaginatedTransactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /**
                     * @description The limit of transactions to get
                     * @default 10
                     */
                    limit?: number;
                    /** @description The cursor to get the next transactions */
                    cursor?: string;
                    /** @description The user ID to get transactions for */
                    userId?: string;
                    /** @description The MU ID to get transactions for */
                    muId?: string;
                    /** @description The country ID to get transactions for */
                    countryId?: string;
                    /** @description The party ID to get transactions for */
                    partyId?: string;
                    /** @description The item code to get transactions for */
                    itemCode?: string;
                    /** @description The type of transactions to get */
                    transactionType?: ("applicationFee" | "trading" | "itemMarket" | "wage" | "donation" | "articleTip" | "openCase" | "craftItem" | "dismantleItem" | "battleLoot") | ("applicationFee" | "trading" | "itemMarket" | "wage" | "donation" | "articleTip" | "openCase" | "craftItem" | "dismantleItem" | "battleLoot")[];
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "upgrade.getUpgradeByTypeAndEntity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /**
                     * @description The upgrade type to get
                     * @enum {string}
                     */
                    upgradeType: "bunker" | "base" | "pacificationCenter" | "storage" | "automatedEngine" | "breakRoom" | "headquarters" | "dormitories";
                    /** @description The region ID to get upgrade for */
                    regionId?: string;
                    /** @description The company ID to get upgrade for */
                    companyId?: string;
                    /** @description The military unit ID to get upgrade for */
                    muId?: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "worker.getWorkers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    companyId?: string;
                    userId?: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "worker.getTotalWorkersCount": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    userId: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "battleOrder.getByBattle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    battleId: string;
                    /** @enum {string} */
                    side: "attacker" | "defender";
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "battleLootSummary.getByBattleAndUser": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    battleId: string;
                    userId: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "inventory.fetchCurrentEquipment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    userId: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "mercenaryContractAuction.getPaginatedAuctions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    countryId?: string;
                    battleId?: string;
                    status?: ("active" | "won" | "expiredNoBids" | "expiredBattle" | "expiredRound" | "cancelled") | "terminated";
                    cursor?: string;
                    limit?: number;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
