import type { OperationKey } from "./types";

export const SAMPLE_SIZE = 10;

export const operationOrder: OperationKey[] = [
  "gameConfig.getDates",
  "gameConfig.getGameConfig",
  "itemTrading.getPrices",
  "region.getRegionsObject",
  "country.getAllCountries",
  "company.getCompanies",
  "ranking.getRanking",
  "search.searchAnything",
  "event.getEventsPaginated",
  "battle.getBattles",
  "mu.getManyPaginated",
  "article.getArticlesPaginated",
  "workOffer.getWorkOffersPaginated",
  "transaction.getPaginatedTransactions",
];

export const allOperations: OperationKey[] = [
  "company.getById",
  "company.getCompanies",
  "country.getCountryById",
  "country.getAllCountries",
  "event.getEventsPaginated",
  "government.getByCountryId",
  "region.getById",
  "region.getRegionsObject",
  "battle.getById",
  "battle.getLiveBattleData",
  "battle.getBattles",
  "round.getById",
  "round.getLastHits",
  "battleRanking.getRanking",
  "itemTrading.getPrices",
  "tradingOrder.getTopOrders",
  "workOffer.getById",
  "workOffer.getWorkOfferByCompanyId",
  "workOffer.getWorkOffersPaginated",
  "ranking.getRanking",
  "search.searchAnything",
  "gameConfig.getDates",
  "gameConfig.getGameConfig",
  "user.getUserLite",
  "user.getUsersByCountry",
  "article.getArticleById",
  "article.getArticleLiteById",
  "article.getArticlesPaginated",
  "mu.getById",
  "mu.getManyPaginated",
  "transaction.getPaginatedTransactions",
  "upgrade.getUpgradeByTypeAndEntity",
  "worker.getWorkers",
  "worker.getTotalWorkersCount",
];
